; Installer script for EasyOKAPI
; Requires NSIS 3.0 or later

!define APP_NAME "EasyOKAPI"
; APP_VERSION must be passed at compile time: makensis /DAPP_VERSION=x.x.x setup.nsi
!ifndef APP_VERSION
  !error "APP_VERSION is not defined. Pass it with: makensis /DAPP_VERSION=x.x.x setup.nsi"
!endif
!define INSTALL_DIR "$PROGRAMFILES\EasyOKAPI"
!define RUNNER_NAME "${APP_NAME}"
!define MUI_ICON "setup.ico"
!define MUI_UNICON "setup.ico"

; ── Branding bitmaps (generated by installer-win/build-bitmaps.sh) ────────────
; sidebar.bmp : 164 × 314 px, HTBiotec logo — shown on Welcome & Finish pages
; header.bmp  : 150 ×  57 px, DNA hexagon icon — shown in every page header
!define MUI_WELCOMEFINISHPAGE_BITMAP "sidebar.bmp"
!define MUI_HEADERIMAGE
!define MUI_HEADERIMAGE_BITMAP "header.bmp"
!define MUI_HEADERIMAGE_RIGHT

; ── Modern UI look & feel ──────────────────────────────────────────────────────
!define MUI_ABORTWARNING
!define MUI_ABORTWARNING_TEXT "Are you sure you want to cancel the EasyOKAPI installation?"

; Welcome page customisation
!define MUI_WELCOMEPAGE_TITLE "Welcome to EasyOKAPI Setup"
!define MUI_WELCOMEPAGE_TEXT "This wizard will guide you through the installation of EasyOKAPI ${APP_VERSION}.$\r$\n$\r$\nThe installer will download all required components automatically. Please ensure you have an internet connection and your EasyOKAPI token ready.$\r$\n$\r$\nClick Next to continue."

; Finish page — offer to launch the application immediately
!define MUI_FINISHPAGE_TITLE "EasyOKAPI ${APP_VERSION} Installed"
!define MUI_FINISHPAGE_TEXT "EasyOKAPI has been successfully installed.$\r$\n$\r$\nA shortcut has been created on your Desktop. Click Finish to close the installer."
!define MUI_FINISHPAGE_RUN "$INSTDIR\${RUNNER_NAME}.exe"
!define MUI_FINISHPAGE_RUN_TEXT "Launch EasyOKAPI now"

; Request admin privileges
RequestExecutionLevel admin

; Set the compression method
SetCompressor lzma

; Installer metadata
Name "${APP_NAME} ${APP_VERSION}"
OutFile "EasyOKAPI_Setup.exe"
InstallDir "${INSTALL_DIR}"
BrandingText "EasyOKAPI ${APP_VERSION}"
ShowInstDetails show
ShowUninstDetails show

; Includes
!include "MUI2.nsh"
!include "nsDialogs.nsh"
!include "WinMessages.nsh"
!include "LogicLib.nsh"

; Variables
Var Dialog
Var TokenInput
Var EasyOKAPIToken

; ── Page order ─────────────────────────────────────────────────────────────────
; Welcome → Token → Directory → Install → Finish
!insertmacro MUI_PAGE_WELCOME
Page custom TokenPage TokenPageLeave
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_WELCOME
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_UNPAGE_FINISH

; Set language
!insertmacro MUI_LANGUAGE "English"

; ── EasyOKAPI token page ───────────────────────────────────────────────────────
Function TokenPage
  !insertmacro MUI_HEADER_TEXT "EasyOKAPI Token" "Enter your Generated EasyOKAPI Token to download the application."
  nsDialogs::Create 1018
  Pop $Dialog
  ${If} $Dialog == error
    Abort
  ${EndIf}

  ${NSD_CreateLabel} 0 0 100% 24u "Please enter your Generated EasyOKAPI Token:"
  Pop $0
  ${NSD_CreateText} 0 26u 100% 12u ""
  Pop $TokenInput
  nsDialogs::Show
FunctionEnd

Function TokenPageLeave
  ${NSD_GetText} $TokenInput $EasyOKAPIToken
  ${If} $EasyOKAPIToken == ""
    MessageBox MB_OK|MB_ICONEXCLAMATION "Please enter a valid EasyOKAPI token."
    Abort
  ${EndIf}
FunctionEnd

; ── Install section ────────────────────────────────────────────────────────────
Section "Install" SEC01
  SetOutPath "$INSTDIR"

  ; Copy batch files and launcher
  File "startwindow-0-clone-repo.bat"
  File "startwindow-2-pyenv.bat"
  File "startwindow-3-python.bat"
  File "startwindow-4-venv.bat"
  File "startwindow-5-run.bat"
  File "EasyOKAPI.exe"
  File "ht.ico"

  ; ── All setup steps run inside NSIS — no separate cmd windows ─────────────
  ; nsExec::ExecToLog runs commands hidden and streams output to the detail list.

  DetailPrint "——————————————————————————————————————"
  DetailPrint "Step 1 / 3  —  Downloading application"
  DetailPrint "——————————————————————————————————————"
  ; Write token to a temp file so special characters (!, &, ^, etc.) are never
  ; interpreted by cmd.exe's command-line parser.  The batch file reads it back
  ; with FOR /F and deletes it immediately — it never touches the install tree.
  FileOpen $R9 "$TEMP\easyokapi_tkn.tmp" w
  FileWrite $R9 "$EasyOKAPIToken"
  FileClose $R9
  nsExec::ExecToLog '"cmd.exe" /c ""$INSTDIR\startwindow-0-clone-repo.bat" "$INSTDIR\code""'
  Pop $0
  Delete "$TEMP\easyokapi_tkn.tmp"
  ${If} $0 != 0
    MessageBox MB_OK|MB_ICONSTOP "Download failed (exit code $0).$\r$\nPlease check your token and internet connection, then re-run Setup."
    Abort
  ${EndIf}
  DetailPrint "Application downloaded successfully."

  DetailPrint "——————————————————————————————————————"
  DetailPrint "Step 2 / 3  —  Installing pyenv & Python"
  DetailPrint "——————————————————————————————————————"
  nsExec::ExecToLog '"cmd.exe" /c "$INSTDIR\startwindow-2-pyenv.bat"'
  Pop $0
  ${If} $0 != 0
    MessageBox MB_OK|MB_ICONSTOP "pyenv setup failed (exit code $0).$\r$\nCheck that you have an internet connection and re-run Setup."
    Abort
  ${EndIf}
  nsExec::ExecToLog '"cmd.exe" /c "$INSTDIR\startwindow-3-python.bat"'
  Pop $0
  ${If} $0 != 0
    MessageBox MB_OK|MB_ICONSTOP "Python installation failed (exit code $0).$\r$\nCheck the Detail log above for the error, then re-run Setup."
    Abort
  ${EndIf}
  DetailPrint "Python ready."

  DetailPrint "——————————————————————————————————————"
  DetailPrint "Step 3 / 3  —  Setting up virtual environment"
  DetailPrint "——————————————————————————————————————"
  nsExec::ExecToLog '"cmd.exe" /c "$INSTDIR\startwindow-4-venv.bat"'
  Pop $0
  ${If} $0 != 0
    MessageBox MB_OK|MB_ICONSTOP "Virtual environment setup failed (exit code $0).$\r$\nCheck the Detail log above for the error, then re-run Setup."
    Abort
  ${EndIf}
  DetailPrint "Virtual environment ready."

  ; Create desktop shortcut and write uninstaller
  CreateShortCut "$DESKTOP\${APP_NAME}.lnk" "$INSTDIR\${RUNNER_NAME}.exe"
  WriteUninstaller "$INSTDIR\Uninstall.exe"

  DetailPrint ""
  DetailPrint "EasyOKAPI ${APP_VERSION} installed successfully."
SectionEnd

; ── Uninstall section ──────────────────────────────────────────────────────────
Section "Uninstall"
  ExecWait 'net stop "${RUNNER_NAME}"'
  ExecWait '"$INSTDIR\nssm.exe" remove "${RUNNER_NAME}" confirm'
  Delete "$SMPROGRAMS\${APP_NAME}\*.*"
  RMDir "$SMPROGRAMS\${APP_NAME}"

  ; Preserve user data before wiping the install directory
  CreateDirectory "$DOCUMENTS\EasyOKAPI_data"
  IfFileExists "$INSTDIR\code\data\*.*" 0 +2
    CopyFiles /SILENT "$INSTDIR\code\data" "$DOCUMENTS\EasyOKAPI_data\data"
  IfFileExists "$INSTDIR\code\json\*.*" 0 +2
    CopyFiles /SILENT "$INSTDIR\code\json" "$DOCUMENTS\EasyOKAPI_data\json"
  IfFileExists "$INSTDIR\code\report\*.*" 0 +2
    CopyFiles /SILENT "$INSTDIR\code\report" "$DOCUMENTS\EasyOKAPI_data\report"
  MessageBox MB_OK "Your measurement data, calibration curves, and reports have been saved to:$\r$\n$DOCUMENTS\EasyOKAPI_data"

  Delete "$INSTDIR\startwindow-0-clone-repo.bat"
  Delete "$INSTDIR\startwindow-2-pyenv.bat"
  Delete "$INSTDIR\startwindow-3-python.bat"
  Delete "$INSTDIR\startwindow-4-venv.bat"
  Delete "$INSTDIR\startwindow-5-run.bat"
  Delete "$INSTDIR\${RUNNER_NAME}.exe"
  Delete "$INSTDIR\ht.ico"
  Delete "$INSTDIR\code\*.*"
  Delete "$DESKTOP\${APP_NAME}.lnk"
  Delete "$INSTDIR\Uninstall.exe"

  RMDir /r "$INSTDIR"
SectionEnd
