; Installer script for EasyOKAPI
; Requires NSIS 3.0 or later

!define APP_NAME "EasyOKAPI"
; APP_VERSION must be passed at compile time: makensis /DAPP_VERSION=x.x.x setup.nsi
!ifndef APP_VERSION
  !error "APP_VERSION is not defined. Pass it with: makensis /DAPP_VERSION=x.x.x setup.nsi"
!endif
; AUTH_BASE_URL must be passed at compile time: makensis /DAUTH_BASE_URL=https://... setup.nsi
!ifndef AUTH_BASE_URL
  !error "AUTH_BASE_URL is not defined. Pass it with: makensis /DAUTH_BASE_URL=https://... setup.nsi"
!endif
!define INSTALL_DIR "$PROGRAMFILES64\EasyOKAPI"
!define RUNNER_NAME "${APP_NAME}"
!define MUI_ICON "setup.ico"
!define MUI_UNICON "setup.ico"

; ── Branding bitmaps (generated by installer-win/build-bitmaps.sh) ────────────
; sidebar.bmp : 164 × 314 px, HTBiotec logo — shown on Welcome & Finish pages
; header.bmp  : 150 ×  57 px, DNA hexagon icon — shown in every page header
!define MUI_WELCOMEFINISHPAGE_BITMAP "sidebar.bmp"
!define MUI_HEADERIMAGE
!define MUI_HEADERIMAGE_BITMAP "header.bmp"
!define MUI_HEADERIMAGE_RIGHT

; ── Dark-theme colour palette ─────────────────────────────────────────────────
; All hex strings without '#', matching the EasyOKAPI web app CSS variables.
!define CLR_BG     "312E81"  ; indigo-900 — main page background  (#312e81)
!define CLR_FG     "E2E8F0"  ; slate-200  — body text             (#e2e8f0)
!define CLR_INPUT  "1E1B4B"  ; indigo-950 — input field bg        (#1e1b4b)
!define CLR_ACCENT "6366F1"  ; indigo-500 — buttons & accents     (#6366f1)

; ── Modern UI look & feel ──────────────────────────────────────────────────────
!define MUI_ABORTWARNING
!define MUI_ABORTWARNING_TEXT "Are you sure you want to cancel the EasyOKAPI installation?"

; Welcome page customisation
!define MUI_WELCOMEPAGE_TITLE "Welcome to EasyOKAPI Setup"
!define MUI_WELCOMEPAGE_TEXT "This wizard will guide you through the installation of EasyOKAPI ${APP_VERSION}.$\r$\n$\r$\nThe installer will download all required components automatically. Please ensure you have an internet connection and your EasyOKAPI token ready.$\r$\n$\r$\nClick Next to continue."

; Finish page — offer to launch the application immediately
!define MUI_FINISHPAGE_TITLE "EasyOKAPI ${APP_VERSION} Installed"
!define MUI_FINISHPAGE_TEXT "EasyOKAPI has been successfully installed.$\r$\n$\r$\nA shortcut has been created on your Desktop.$\r$\n$\r$\nA backup of measurement data, calibration curves, and reports from any previous installation is kept in your Documents folder under EasyOKAPI_data. If you reinstalled after uninstalling, tick the box below to import that data into this version, then click Finish."
!define MUI_FINISHPAGE_RUN "$INSTDIR\${RUNNER_NAME}.exe"
!define MUI_FINISHPAGE_RUN_TEXT "Launch EasyOKAPI now"

; Second finish-page checkbox — the MUI "show readme" checkbox is repurposed
; via SHOWREADME_FUNCTION to import user data preserved from a previous
; installation (Documents\EasyOKAPI_data) into this freshly installed version.
; Unchecked by default so a normal upgrade — whose data is already auto-restored
; during install — is never touched unless the user explicitly opts in.
!define MUI_FINISHPAGE_SHOWREADME ""
!define MUI_FINISHPAGE_SHOWREADME_NOTCHECKED
!define MUI_FINISHPAGE_SHOWREADME_TEXT "Import data from a previous EasyOKAPI backup"
!define MUI_FINISHPAGE_SHOWREADME_FUNCTION RestoreBackupData

; Request admin privileges
RequestExecutionLevel admin

; Set the compression method
SetCompressor lzma

; ── Molecular biology background images (generated by build-bitmaps.py) ──────
; background.bmp (1280x720) — full-screen image rendered by BgImage behind the
;   installer window for the whole session.
; page_bg.bmp   (432x314)   — pre-scaled version of background.bmp sized to the
;   MUI2 inner-dialog dimensions (432 px wide × sidebar height 314 px).  Loaded
;   at native size in page SHOW callbacks so LoadImageW never has to rescale a
;   large source bitmap, which is unreliable on some NSIS / Windows builds.
ReserveFile "background.bmp"
ReserveFile "page_bg.bmp"

; ── Install-log text / background on the InstFiles detail area ─────────────────
InstallColors E2E8F0 312E81

; Installer metadata
Name "${APP_NAME} ${APP_VERSION}"
OutFile "EasyOKAPI_Setup.exe"
InstallDir "${INSTALL_DIR}"
BrandingText "EasyOKAPI ${APP_VERSION}"
ShowInstDetails show
ShowUninstDetails show

; Includes
!include "MUI2.nsh"
!include "nsDialogs.nsh"
!include "WinMessages.nsh"
!include "LogicLib.nsh"

; Variables
Var Dialog
Var TokenInput
Var EasyOKAPIToken
Var BgBitmapHandle

; ── Page order ─────────────────────────────────────────────────────────────────
; Welcome → Token → Directory → Install → Finish
; Each built-in MUI page gets a SHOW callback that recolours all inner controls.
!define MUI_PAGE_CUSTOMFUNCTION_SHOW _DarkWelcomePage
!insertmacro MUI_PAGE_WELCOME

Page custom TokenPage TokenPageLeave

!define MUI_PAGE_CUSTOMFUNCTION_SHOW _DarkPage
!insertmacro MUI_PAGE_DIRECTORY

!define MUI_PAGE_CUSTOMFUNCTION_SHOW _DarkInstPage
!insertmacro MUI_PAGE_INSTFILES

!define MUI_PAGE_CUSTOMFUNCTION_SHOW _DarkPage
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
; MUI2 does NOT auto-undef MUI_UNPAGE_CUSTOMFUNCTION_SHOW, so we manage it
; manually: reuse the same define for consecutive pages sharing a callback,
; and explicitly !undef before switching to a different one.
!define MUI_UNPAGE_CUSTOMFUNCTION_SHOW _DarkPage
!insertmacro MUI_UNPAGE_WELCOME
!insertmacro MUI_UNPAGE_CONFIRM

!undef MUI_UNPAGE_CUSTOMFUNCTION_SHOW
!define MUI_UNPAGE_CUSTOMFUNCTION_SHOW _DarkInstPage
!insertmacro MUI_UNPAGE_INSTFILES

!undef MUI_UNPAGE_CUSTOMFUNCTION_SHOW
!define MUI_UNPAGE_CUSTOMFUNCTION_SHOW _DarkPage
!insertmacro MUI_UNPAGE_FINISH

; MUI2 owns .onInit and .onGUIInit — use these hooks for our customisations.
; _OnInit    : extract + show the BgImage background before any window appears.
; _OnGUIInit : colour outer chrome, title bar, buttons, and BrandingText strip.
!define MUI_CUSTOMFUNCTION_INIT     _OnInit
!define MUI_CUSTOMFUNCTION_GUIINIT  _OnGUIInit

; Set language
!insertmacro MUI_LANGUAGE "English"

; ── Background image ──────────────────────────────────────────────────────────

; _OnInit — runs inside MUI2's .onInit before any window is created.
; Only extracts background.bmp here; the data stream is accessible at this
; stage.  BgImage::SetBg is intentionally NOT called here because no NSIS
; window exists yet — calling it this early causes BgImage to lose the
; correct Z-order on Windows 10/11 and the background never appears.
; The actual BgImage::SetBg / Redraw calls live in _OnGUIInit below.
Function _OnInit
  InitPluginsDir
  SetOutPath $PLUGINSDIR
  File "background.bmp"
  File "page_bg.bmp"
FunctionEnd

; .onGUIEnd — runs after the installer GUI closes.  Destroys the BgImage window.
Function .onGUIEnd
  BgImage::Destroy
FunctionEnd

; ── Dark-theme helpers ─────────────────────────────────────────────────────────

; _DarkWelcomePage — SHOW callback for the Welcome page.
; Applies the full indigo dark theme first (via _DarkPage) so the page always
; looks correct.  Then attempts to inject a scaled background.bmp behind the
; inner-dialog controls.  If LoadImageW returns 0 (file not yet extracted,
; unsupported scale, etc.) the blank control is destroyed and the indigo
; fallback remains untouched.  SS_BITMAP controls (MUI2 sidebar with the okapi
; mascot) are skipped so they stay visible.
Function _DarkWelcomePage
  ; Reliable indigo fallback — run _DarkPage first so the page is never white.
  Call _DarkPage

  Push $R6
  Push $R7
  Push $R8
  Push $R9

  FindWindow $R8 "#32770" "" $HWNDPARENT
  ${If} $R8 != 0
    ; Query inner dialog client area for bitmap scaling.
    System::Alloc 16
    Pop $R9
    System::Call 'user32::GetClientRect(i $R8, i $R9)'
    System::Call '*$R9(i, i, i .r0, i .r1)'   ; r0 = width, r1 = height
    System::Free $R9

    ; Create STATIC SS_BITMAP control sized to the full inner dialog.
    System::Call 'user32::CreateWindowExW(i 0, t "STATIC", t "", i 0x5000000E, i 0, i 0, i r0, i r1, i $R8, i 0, i 0, i 0) i .R7'

    ; Load page_bg.bmp at its native size (cx=0, cy=0 — no scaling requested).
    ; page_bg.bmp is pre-scaled to 432x314 by build-bitmaps.py so LoadImageW
    ; never has to rescale a large source, which is unreliable on some builds.
    System::Call 'user32::LoadImageW(i 0, t "$PLUGINSDIR\page_bg.bmp", i 0, i 0, i 0, i 0x10) i .R6'

    ${If} $R6 != 0
      SendMessage $R7 0x172 0 $R6   ; STM_SETIMAGE (0x172), IMAGE_BITMAP (0)
      ; Push bitmap control to Z-order bottom; resize to dialog dims in same call.
      ; HWND_BOTTOM=1, flags=0 → position + size + z-order all applied.
      System::Call 'user32::SetWindowPos(i $R7, i 1, i 0, i 0, i r0, i r1, i 0)'

      ; Make text/label controls transparent so the bitmap shows through.
      ; Skip our injected bitmap ($R7) and any SS_BITMAP controls (sidebar).
      ; $R6 is free to reuse for the style check after the HBITMAP is set.
      StrCpy $R9 0
      _dwp_loop:
        System::Call 'user32::FindWindowEx(i $R8, i $R9, i 0, i 0) i .R9'
        ${If} $R9 == 0
          Goto _dwp_done
        ${EndIf}
        ${If} $R9 == $R7
          Goto _dwp_loop
        ${EndIf}
        System::Call 'user32::GetWindowLongW(i $R9, i -16) i .R6'
        IntOp $R6 $R6 & 0xF
        ${If} $R6 == 0xE   ; SS_BITMAP — leave sidebar.bmp alone
          Goto _dwp_loop
        ${EndIf}
        SetCtlColors $R9 "${CLR_FG}" "transparent"
        Goto _dwp_loop
      _dwp_done:

      System::Call 'user32::InvalidateRect(i $R8, i 0, i 1)'
    ${Else}
      ; LoadImageW failed — destroy the blank control; indigo from _DarkPage remains.
      System::Call 'user32::DestroyWindow(i $R7)'
    ${EndIf}
  ${EndIf}

  Pop $R9
  Pop $R8
  Pop $R7
  Pop $R6

  Call _DarkButtons
FunctionEnd

; _DarkPage — called from every page SHOW callback.
; Two-level walk: strips visual theme and applies dark palette to every
; direct child of the MUI2 inner dialog, then repeats for each grandchild
; (e.g. the Browse button and path edit inside the Destination Folder groupbox).
Function _DarkPage
  Push $R6
  Push $R7
  Push $R8
  Push $R9

  FindWindow $R8 "#32770" "" $HWNDPARENT
  ${If} $R8 == 0
    Pop $R9
    Pop $R8
    Pop $R7
    Pop $R6
    Return
  ${EndIf}
  SetCtlColors $R8 "${CLR_FG}" "${CLR_BG}"

  ; ── Level 1: direct children ─────────────────────────────────────────────
  StrCpy $R9 0
  _dp_loop:
    System::Call 'user32::FindWindowEx(i $R8, i $R9, i 0, i 0) i .R9'
    ${If} $R9 == 0
      Goto _dp_done
    ${EndIf}
    ; Strip visual theme so SetCtlColors is honoured (fixes groupbox border)
    System::Call 'uxtheme::SetWindowTheme(i $R9, w " ", w " ")'
    SetCtlColors $R9 "${CLR_FG}" "${CLR_BG}"

    ; ── Level 2: grandchildren (controls nested inside groupboxes) ──────────
    StrCpy $R7 0
    _dp_gc_loop:
      System::Call 'user32::FindWindowEx(i $R9, i $R7, i 0, i 0) i .R7'
      ${If} $R7 == 0
        Goto _dp_gc_done
      ${EndIf}
      System::Call 'uxtheme::SetWindowTheme(i $R7, w " ", w " ")'
      SetCtlColors $R7 "${CLR_FG}" "${CLR_INPUT}"
      Goto _dp_gc_loop
    _dp_gc_done:

    Goto _dp_loop
  _dp_done:

  Pop $R9
  Pop $R8
  Pop $R7
  Pop $R6
FunctionEnd

; _DarkInstPage — same as _DarkPage plus progress-bar colour overrides.
; Removes the visual theme from the progress bar first (required on Vista+
; so that PBM_SETBARCOLOR is not silently ignored by the themed renderer).
Function _DarkInstPage
  Call _DarkPage

  Push $R7
  Push $R8

  FindWindow $R8 "#32770" "" $HWNDPARENT
  ${If} $R8 == 0
    Pop $R8
    Pop $R7
    Return
  ${EndIf}

  ; Locate the progress bar by class name
  System::Call 'user32::FindWindowEx(i $R8, i 0, t "msctls_progress32", i 0) i .R7'
  ${If} $R7 != 0
    ; Strip the visual theme so custom colours take effect
    System::Call 'uxtheme::SetWindowTheme(i $R7, w " ", w " ")'
    ; PBM_SETBARCOLOR (0x0409) — bar fill: indigo-500 as COLORREF 0x00F16663
    SendMessage $R7 0x0409 0 0x00F16663
    ; PBM_SETBKCOLOR  (0x2001) — track bg:  slate-900 as COLORREF 0x002A170F
    SendMessage $R7 0x2001 0 0x002A170F
  ${EndIf}

  ; Detail log: apply indigo bg and re-enable DarkMode_Explorer theme so
  ; Windows renders the scrollbar in dark style on Win10 20H1+/Win11.
  ; _DarkPage stripped the theme with " "/" "; restore it here specifically
  ; for this control.  Try RichEdit20W (NSIS 3.x) then EDIT as fallback.
  System::Call 'user32::FindWindowEx(i $R8, i 0, t "RichEdit20W", i 0) i .R7'
  ${If} $R7 == 0
    System::Call 'user32::FindWindowEx(i $R8, i 0, t "EDIT", i 0) i .R7'
  ${EndIf}
  ${If} $R7 != 0
    System::Call 'uxtheme::SetWindowTheme(i $R7, w "DarkMode_Explorer", i 0)'
    SetCtlColors $R7 "${CLR_FG}" "${CLR_BG}"
  ${EndIf}

  Pop $R8
  Pop $R7
FunctionEnd

; _DarkButtons — strips visual theme and applies indigo fill to every
; BUTTON-class direct child of the outer installer window (Next/Back/Cancel).
Function _DarkButtons
  Push $R0
  StrCpy $R0 0
  _dbtn_loop:
    System::Call 'user32::FindWindowEx(i $HWNDPARENT, i $R0, t "Button", i 0) i .R0'
    ${If} $R0 == 0
      Goto _dbtn_done
    ${EndIf}
    System::Call 'uxtheme::SetWindowTheme(i $R0, w " ", w " ")'
    SetCtlColors $R0 "${CLR_FG}" "${CLR_ACCENT}"
    Goto _dbtn_loop
  _dbtn_done:
  Pop $R0
FunctionEnd

; Called by MUI2's .onGUIInit — colours outer chrome, title bar, buttons,
; and the BrandingText ("EasyOKAPI x.x.x") strip at the bottom.
; BgImage is started here (not in _OnInit) so that the NSIS outer window
; already exists when BgImage creates its background window — this gives
; the correct Z-order on Windows 10/11 so the background is visible.
Function _OnGUIInit
  BgImage::SetBg /NOUNLOAD "$PLUGINSDIR\background.bmp"
  BgImage::Redraw /NOUNLOAD

  SetCtlColors $HWNDPARENT "${CLR_FG}" "${CLR_BG}"

  ; Title bar via DWM (Win10 20H1+ / Win11; silently ignored on older builds).
  ; DWMWA_CAPTION_COLOR=35, DWMWA_TEXT_COLOR=36. COLORREF 0x00BBGGRR:
  ;   indigo-500 #6366F1 -> 0x00F16663   white -> 0x00FFFFFF
  System::Call 'dwmapi::DwmSetWindowAttribute(i $HWNDPARENT, i 35, *i 0x00F16663, i 4)'
  System::Call 'dwmapi::DwmSetWindowAttribute(i $HWNDPARENT, i 36, *i 0x00FFFFFF, i 4)'

  Call _DarkButtons

  ; Style the BrandingText strip — walk every Static-class child of the outer
  ; window and apply a matching dark bg with soft indigo-300 text (#a5b4fc).
  ; This removes the white-box appearance and renders the version as a
  ; styled tag that harmonises with the indigo sidebar gradient.
  Push $R0
  StrCpy $R0 0
  _branding_loop:
    System::Call 'user32::FindWindowEx(i $HWNDPARENT, i $R0, t "Static", i 0) i .R0'
    ${If} $R0 == 0
      Goto _branding_done
    ${EndIf}
    SetCtlColors $R0 "A5B4FC" "${CLR_BG}"
    Goto _branding_loop
  _branding_done:
  Pop $R0
FunctionEnd

; ── EasyOKAPI token page ───────────────────────────────────────────────────────
Function TokenPage
  !insertmacro MUI_HEADER_TEXT "EasyOKAPI Token" "Enter your Generated EasyOKAPI Token to download the application."
  nsDialogs::Create 1018
  Pop $Dialog
  ${If} $Dialog == error
    Abort
  ${EndIf}

  ; Indigo fallback — same pattern as _DarkWelcomePage: stamp the dark theme
  ; first so the page is never white even if NSD_SetStretchedImage returns 0.
  SetCtlColors $Dialog "${CLR_FG}" "${CLR_BG}"

  ; Background bitmap — created first so it sits at the back of the Z-order.
  ; Use page_bg.bmp (432x314, pre-scaled) so NSD_SetStretchedImage only has to
  ; scale a small source bitmap, which LoadImageW handles reliably.
  ${NSD_CreateBitmap} 0 0 100% 100% ""
  Pop $0
  ${NSD_SetStretchedImage} $0 "$PLUGINSDIR\page_bg.bmp" $BgBitmapHandle

  ${NSD_CreateLabel} 0 0 100% 24u "Please enter your Generated EasyOKAPI Token:"
  Pop $0
  SetCtlColors $0 "${CLR_FG}" "${CLR_BG}"

  ${NSD_CreateText} 0 26u 100% 12u ""
  Pop $TokenInput
  SetCtlColors $TokenInput "${CLR_FG}" "${CLR_INPUT}"

  ; Re-style the outer navigation buttons — mirrors _DarkWelcomePage's call to
  ; _DarkButtons so the Next/Cancel buttons keep their indigo style on this page.
  Call _DarkButtons

  nsDialogs::Show
FunctionEnd

Function TokenPageLeave
  ${NSD_GetText} $TokenInput $EasyOKAPIToken
  ${If} $EasyOKAPIToken == ""
    MessageBox MB_OK|MB_ICONEXCLAMATION "Please enter a valid EasyOKAPI token."
    Abort
  ${EndIf}
FunctionEnd

; ── Finish-page: import data from a previous installation ──────────────────────
; Wired to the repurposed SHOWREADME checkbox. Copies measurement data,
; calibration JSON, and reports from the persistent backup folder
; ($DOCUMENTS\EasyOKAPI_data) — written by the uninstaller and by the update
; path of this installer — into the freshly installed code directory.
Function RestoreBackupData
  StrCpy $R6 "$DOCUMENTS\EasyOKAPI_data"
  IfFileExists "$R6\*.*" 0 rbd_none
    IfFileExists "$R6\data\*.*" 0 +2
      CopyFiles /SILENT "$R6\data" "$INSTDIR\code\data"
    IfFileExists "$R6\json\*.*" 0 +2
      CopyFiles /SILENT "$R6\json" "$INSTDIR\code\json"
    IfFileExists "$R6\report\*.*" 0 +2
      CopyFiles /SILENT "$R6\report" "$INSTDIR\code\report"
    MessageBox MB_OK|MB_ICONINFORMATION "Your previous EasyOKAPI data has been imported from:$\r$\n$R6$\r$\n$\r$\nThe backup folder has been kept in case you need it again."
    Return
  rbd_none:
    MessageBox MB_OK|MB_ICONINFORMATION "No previous EasyOKAPI backup was found at:$\r$\n$R6$\r$\n$\r$\nThere is nothing to import."
FunctionEnd

; ── Install section ────────────────────────────────────────────────────────────
Section "Install" SEC01
  SetOutPath "$INSTDIR"

  ; Copy batch files and launcher
  File "startwindow-0-clone-repo.bat"
  File "startwindow-1-git.bat"
  File "startwindow-2-pyenv.bat"
  File "startwindow-3-python.bat"
  File "startwindow-4-venv.bat"
  File "startwindow-5-run.bat"
  File "launcher.ps1"
  File "EasyOKAPI.exe"
  File "ht.ico"

  ; nsExec::ExecToLog streams each child-process stdout/stderr directly to the
  ; NSIS detail log — no intermediate bat wrapper needed for Step 1.

  ; ── Resolve short paths (avoids spaces / parens breaking cmd.exe args) ────────
  System::Call 'kernel32::GetShortPathNameW(w "$INSTDIR", w .r11, i 1024)'
  ${If} $R1 == ""
    StrCpy $R1 "$INSTDIR"
  ${EndIf}
  System::Call 'kernel32::GetShortPathNameW(w "$TEMP", w .r12, i 1024)'
  ${If} $R2 == ""
    StrCpy $R2 "$TEMP"
  ${EndIf}
  StrCpy $R3 "$R1\code"                 ; code destination directory
  StrCpy $R4 "$R2\easyokapi_app.tar.gz" ; temp download archive

  ; ── Inject token into child-process environment ───────────────────────────────
  StrCpy $R0 "$EasyOKAPIToken"
  System::Call 'Kernel32::SetEnvironmentVariableW(w "EASYOKAPI_DOWNLOAD_TOKEN", w r10) i .r1'
  ${If} $1 == 0
    MessageBox MB_OK|MB_ICONSTOP "Installer error: could not set download token in process environment.$\r$\nPlease re-run Setup."
    Abort
  ${EndIf}

  ; ── Step 1 / 4  -  Downloading application ───────────────────────────────────
  DetailPrint "======================================"
  DetailPrint "Step 1 / 4  -  Downloading application"
  DetailPrint "======================================"

  ; Detect existing installation and ask the user what to do.
  StrCpy $R5 "0"
  StrCpy $R6 ""
  IfFileExists "$R3" 0 step1_fresh      ; exists → fall through; absent → jump

    ; Read the installed version from VERSION.txt (if present).
    StrCpy $R7 "Unknown"
    IfFileExists "$R3\VERSION.txt" 0 +4
      FileOpen $8 "$R3\VERSION.txt" r
      FileRead $8 $R7
      FileClose $8

    ; Ask the user: update or keep?
    MessageBox MB_YESNO|MB_ICONQUESTION \
      "An existing EasyOKAPI installation was found:$\r$\n\
$\r$\n\
    Location:        $R3$\r$\n\
    Current version: $R7$\r$\n\
    New version:     v${APP_VERSION}$\r$\n\
$\r$\n\
Update to v${APP_VERSION}? (Your data will be preserved.) \
Click No to keep the existing installation and cancel Setup." \
      IDYES step1_do_overwrite
      Abort   ; user chose No → exit installer cleanly
    step1_do_overwrite:

    ; Stop any EasyOKAPI Python still running from this install. A live instance
    ; keeps its venv python.exe/DLLs open, so the RMDir below only partially
    ; deletes the venv and the later "pip install" fails with [WinError 5]
    ; Access is denied, shipping a broken app. The PowerShell is written to a
    ; temp file (rather than inlined) to avoid NSIS/PowerShell quote escaping.
    DetailPrint "Stopping any running EasyOKAPI instance..."
    FileOpen $9 "$PLUGINSDIR\stop-easyokapi.ps1" w
    FileWrite $9 '$$r = $$args[0]$\r$\n'
    FileWrite $9 'Get-CimInstance Win32_Process | Where-Object { ($$_.Name -eq ''python.exe'' -or $$_.Name -eq ''pythonw.exe'') -and $$_.ExecutablePath -and $$_.ExecutablePath.StartsWith($$r,[System.StringComparison]::OrdinalIgnoreCase) } | ForEach-Object { Stop-Process -Id $$_.ProcessId -Force -ErrorAction SilentlyContinue }$\r$\n'
    FileWrite $9 'Start-Sleep -Seconds 2$\r$\n'
    FileClose $9
    nsExec::ExecToLog '"powershell.exe" -NoProfile -ExecutionPolicy Bypass -File "$PLUGINSDIR\stop-easyokapi.ps1" "$INSTDIR\"'
    Pop $0

    DetailPrint "Existing installation found — preserving user data..."
    ; Persistent backup folder (also read by the finish-page "Import data" option
    ; and written by the uninstaller). Cleared first so it only ever holds the
    ; most recent installation's data.
    StrCpy $R6 "$DOCUMENTS\EasyOKAPI_data"
    RMDir /r "$R6"
    CreateDirectory "$R6"
    StrCpy $R5 "1"
    IfFileExists "$R3\data\*.*" 0 +2
      CopyFiles /SILENT "$R3\data" "$R6\data"
    IfFileExists "$R3\json\*.*" 0 +2
      CopyFiles /SILENT "$R3\json" "$R6\json"
    IfFileExists "$R3\report\*.*" 0 +2
      CopyFiles /SILENT "$R3\report" "$R6\report"
    DetailPrint "Removing existing code directory for overwrite..."
    RMDir /r "$R3"
  step1_fresh:
  CreateDirectory "$R3"

  ; Download — curl output goes straight to the NSIS detail log.
  DetailPrint "Downloading application archive..."
  nsExec::ExecToLog '"cmd.exe" /c curl --fail -L -o "$R4" "${AUTH_BASE_URL}/api/download?token=%EASYOKAPI_DOWNLOAD_TOKEN%"'
  Pop $0
  ${If} $0 == 255
    MessageBox MB_OK|MB_ICONSTOP "curl could not be launched (exit 255).$\r$\nCheck antivirus / Defender exclusions for $INSTDIR, then re-run Setup."
    Abort
  ${EndIf}
  ${If} $0 != 0
    MessageBox MB_OK|MB_ICONSTOP "Download failed (curl exit $0).$\r$\nCheck your token and internet connection.$\r$\nSee the detail log above for curl's error output."
    Abort
  ${EndIf}

  ; Extract — tar output goes straight to the NSIS detail log.
  DetailPrint "Extracting application archive..."
  nsExec::ExecToLog '"cmd.exe" /c tar -xzf "$R4" -C "$R3" --strip-components=1'
  Pop $0
  Delete "$R4"
  ${If} $0 != 0
    MessageBox MB_OK|MB_ICONSTOP "Extraction failed (tar exit $0).$\r$\nSee the detail log above for more information."
    Abort
  ${EndIf}

  ; Restore preserved user data.
  ${If} $R5 == "1"
    DetailPrint "Restoring user data (data, json, report)..."
    IfFileExists "$R6\data\*.*" 0 +2
      CopyFiles /SILENT "$R6\data" "$R3\data"
    IfFileExists "$R6\json\*.*" 0 +2
      CopyFiles /SILENT "$R6\json" "$R3\json"
    IfFileExists "$R6\report\*.*" 0 +2
      CopyFiles /SILENT "$R6\report" "$R3\report"
    ; Keep $R6 as a persistent safety backup (Documents\EasyOKAPI_data) rather
    ; than deleting it — the finish page tells the user where it is.
    DetailPrint "User data restored. A backup copy is kept at $R6."
  ${EndIf}

  ; Remove development-only files from the extracted archive.
  DetailPrint "Removing development files..."
  Delete "$R3\*.command"
  Delete "$R3\*.bat"
  Delete "$R3\*.sh"
  Delete "$R3\log_hid_data.py"
  Delete "$R3\generate-tree.sh"
  Delete "$R3\BUILD_MAC.md"
  Delete "$R3\Rule.md"
  Delete "$R3\CLAUDE.md"
  Delete "$R3\requirements.txt"
  Delete "$R3\test_browser.py"
  Delete "$R3\.gitignore"
  RMDir /r "$R3\mac"
  RMDir /r "$R3\easyokapi-knowledge"
  RMDir /r "$R3\images"
  RMDir /r "$R3\installer-mac"
  RMDir /r "$R3\installer-win"
  RMDir /r "$R3\installer-linux"
  RMDir /r "$R3\tests"
  RMDir /r "$R3\.github"

  ; Write version and activation files.
  FileOpen $9 "$R3\VERSION.txt" w
  FileWrite $9 "v${APP_VERSION}"
  FileClose $9
  FileOpen $9 "$R3\activation.json" w
  FileWrite $9 '{$\n  "license_token": "$EasyOKAPIToken"$\n}'
  FileClose $9

  DetailPrint "Application downloaded successfully."

  ; ── Step 2 / 4  -  Installing Git ───────────────────────────────────────────
  DetailPrint "======================================"
  DetailPrint "Step 2 / 4  -  Installing Git"
  DetailPrint "======================================"
  nsExec::ExecToLog '"cmd.exe" /c "$R1\startwindow-1-git.bat"'
  Pop $0
  ${If} $0 != 0
    MessageBox MB_OK|MB_ICONSTOP "Git installation failed (exit code $0).$\r$\nCheck your internet connection and re-run Setup."
    Abort
  ${EndIf}
  DetailPrint "Git ready."

  ; ── Step 3 / 4  -  Installing pyenv & Python ─────────────────────────────────
  DetailPrint "======================================"
  DetailPrint "Step 3 / 4  -  Installing pyenv & Python"
  DetailPrint "======================================"
  nsExec::ExecToLog '"cmd.exe" /c "$R1\startwindow-2-pyenv.bat"'
  Pop $0
  ${If} $0 != 0
    MessageBox MB_OK|MB_ICONSTOP "pyenv setup failed (exit code $0).$\r$\nCheck that you have an internet connection and re-run Setup."
    Abort
  ${EndIf}
  nsExec::ExecToLog '"cmd.exe" /c "$R1\startwindow-3-python.bat"'
  Pop $0
  ${If} $0 != 0
    MessageBox MB_OK|MB_ICONSTOP "Python installation failed (exit code $0).$\r$\nCheck the Detail log above for the error, then re-run Setup."
    Abort
  ${EndIf}
  DetailPrint "Python ready."

  DetailPrint "======================================"
  DetailPrint "Step 4 / 4  -  Setting up virtual environment"
  DetailPrint "======================================"
  nsExec::ExecToLog '"cmd.exe" /c "$R1\startwindow-4-venv.bat"'
  Pop $0
  ${If} $0 != 0
    MessageBox MB_OK|MB_ICONSTOP "Virtual environment setup failed (exit code $0).$\r$\nCheck the Detail log above for the error, then re-run Setup."
    Abort
  ${EndIf}
  DetailPrint "Virtual environment ready."

  ; Create desktop shortcut and write uninstaller
  CreateShortCut "$DESKTOP\${APP_NAME}.lnk" "$INSTDIR\${RUNNER_NAME}.exe"
  WriteUninstaller "$INSTDIR\Uninstall.exe"

  DetailPrint ""
  DetailPrint "EasyOKAPI ${APP_VERSION} installed successfully."
SectionEnd

; ── Uninstall section ──────────────────────────────────────────────────────────
Section "Uninstall"
  ExecWait 'net stop "${RUNNER_NAME}"'
  ExecWait '"$INSTDIR\nssm.exe" remove "${RUNNER_NAME}" confirm'
  Delete "$SMPROGRAMS\${APP_NAME}\*.*"
  RMDir "$SMPROGRAMS\${APP_NAME}"

  ; Preserve user data before wiping the install directory
  CreateDirectory "$DOCUMENTS\EasyOKAPI_data"
  IfFileExists "$INSTDIR\code\data\*.*" 0 +2
    CopyFiles /SILENT "$INSTDIR\code\data" "$DOCUMENTS\EasyOKAPI_data\data"
  IfFileExists "$INSTDIR\code\json\*.*" 0 +2
    CopyFiles /SILENT "$INSTDIR\code\json" "$DOCUMENTS\EasyOKAPI_data\json"
  IfFileExists "$INSTDIR\code\report\*.*" 0 +2
    CopyFiles /SILENT "$INSTDIR\code\report" "$DOCUMENTS\EasyOKAPI_data\report"
  MessageBox MB_OK "Your measurement data, calibration curves, and reports have been saved to:$\r$\n$DOCUMENTS\EasyOKAPI_data"

  Delete "$INSTDIR\startwindow-0-clone-repo.bat"
  Delete "$INSTDIR\startwindow-2-pyenv.bat"
  Delete "$INSTDIR\startwindow-3-python.bat"
  Delete "$INSTDIR\startwindow-4-venv.bat"
  Delete "$INSTDIR\startwindow-5-run.bat"
  Delete "$INSTDIR\launcher.ps1"
  Delete "$INSTDIR\${RUNNER_NAME}.exe"
  Delete "$INSTDIR\ht.ico"
  Delete "$INSTDIR\code\*.*"
  Delete "$DESKTOP\${APP_NAME}.lnk"
  Delete "$INSTDIR\Uninstall.exe"

  RMDir /r "$INSTDIR"
SectionEnd
