; Installer script for EasyOKAPI
; Requires NSIS 3.0 or later

!define APP_NAME "EasyOKAPI"
; APP_VERSION must be passed at compile time: makensis /DAPP_VERSION=x.x.x setup.nsi
!ifndef APP_VERSION
  !error "APP_VERSION is not defined. Pass it with: makensis /DAPP_VERSION=x.x.x setup.nsi"
!endif
; AUTH_BASE_URL must be passed at compile time: makensis /DAUTH_BASE_URL=https://... setup.nsi
!ifndef AUTH_BASE_URL
  !error "AUTH_BASE_URL is not defined. Pass it with: makensis /DAUTH_BASE_URL=https://... setup.nsi"
!endif
!define INSTALL_DIR "$PROGRAMFILES64\EasyOKAPI"
!define RUNNER_NAME "${APP_NAME}"
!define MUI_ICON "setup.ico"
!define MUI_UNICON "setup.ico"

; ── Branding bitmaps (generated by installer-win/build-bitmaps.sh) ────────────
; sidebar.bmp : 164 × 314 px, HTBiotec logo — shown on Welcome & Finish pages
; header.bmp  : 150 ×  57 px, DNA hexagon icon — shown in every page header
!define MUI_WELCOMEFINISHPAGE_BITMAP "sidebar.bmp"
!define MUI_HEADERIMAGE
!define MUI_HEADERIMAGE_BITMAP "header.bmp"
!define MUI_HEADERIMAGE_RIGHT

; ── Modern UI look & feel ──────────────────────────────────────────────────────
!define MUI_ABORTWARNING
!define MUI_ABORTWARNING_TEXT "Are you sure you want to cancel the EasyOKAPI installation?"

; Welcome page customisation
!define MUI_WELCOMEPAGE_TITLE "Welcome to EasyOKAPI Setup"
!define MUI_WELCOMEPAGE_TEXT "This wizard will guide you through the installation of EasyOKAPI ${APP_VERSION}.$\r$\n$\r$\nThe installer will download all required components automatically. Please ensure you have an internet connection and your EasyOKAPI token ready.$\r$\n$\r$\nClick Next to continue."

; Finish page — offer to launch the application immediately
!define MUI_FINISHPAGE_TITLE "EasyOKAPI ${APP_VERSION} Installed"
!define MUI_FINISHPAGE_TEXT "EasyOKAPI has been successfully installed.$\r$\n$\r$\nA shortcut has been created on your Desktop. Click Finish to close the installer."
!define MUI_FINISHPAGE_RUN "$INSTDIR\${RUNNER_NAME}.exe"
!define MUI_FINISHPAGE_RUN_TEXT "Launch EasyOKAPI now"

; Request admin privileges
RequestExecutionLevel admin

; Set the compression method
SetCompressor lzma

; Installer metadata
Name "${APP_NAME} ${APP_VERSION}"
OutFile "EasyOKAPI_Setup.exe"
InstallDir "${INSTALL_DIR}"
BrandingText "EasyOKAPI ${APP_VERSION}"
ShowInstDetails show
ShowUninstDetails show

; Includes
!include "MUI2.nsh"
!include "nsDialogs.nsh"
!include "WinMessages.nsh"
!include "LogicLib.nsh"

; Variables
Var Dialog
Var TokenInput
Var EasyOKAPIToken

; ── Page order ─────────────────────────────────────────────────────────────────
; Welcome → Token → Directory → Install → Finish
!insertmacro MUI_PAGE_WELCOME
Page custom TokenPage TokenPageLeave
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_WELCOME
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_UNPAGE_FINISH

; Set language
!insertmacro MUI_LANGUAGE "English"

; ── EasyOKAPI token page ───────────────────────────────────────────────────────
Function TokenPage
  !insertmacro MUI_HEADER_TEXT "EasyOKAPI Token" "Enter your Generated EasyOKAPI Token to download the application."
  nsDialogs::Create 1018
  Pop $Dialog
  ${If} $Dialog == error
    Abort
  ${EndIf}

  ${NSD_CreateLabel} 0 0 100% 24u "Please enter your Generated EasyOKAPI Token:"
  Pop $0
  ${NSD_CreateText} 0 26u 100% 12u ""
  Pop $TokenInput
  nsDialogs::Show
FunctionEnd

Function TokenPageLeave
  ${NSD_GetText} $TokenInput $EasyOKAPIToken
  ${If} $EasyOKAPIToken == ""
    MessageBox MB_OK|MB_ICONEXCLAMATION "Please enter a valid EasyOKAPI token."
    Abort
  ${EndIf}
FunctionEnd

; ── Install section ────────────────────────────────────────────────────────────
Section "Install" SEC01
  SetOutPath "$INSTDIR"

  ; Copy batch files and launcher
  File "startwindow-0-clone-repo.bat"
  File "startwindow-2-pyenv.bat"
  File "startwindow-3-python.bat"
  File "startwindow-4-venv.bat"
  File "startwindow-5-run.bat"
  File "launcher.ps1"
  File "EasyOKAPI.exe"
  File "ht.ico"

  ; nsExec::ExecToLog streams each child-process stdout/stderr directly to the
  ; NSIS detail log — no intermediate bat wrapper needed for Step 1.

  ; ── Resolve short paths (avoids spaces / parens breaking cmd.exe args) ────────
  System::Call 'kernel32::GetShortPathNameW(w "$INSTDIR", w .r11, i 1024)'
  ${If} $R1 == ""
    StrCpy $R1 "$INSTDIR"
  ${EndIf}
  System::Call 'kernel32::GetShortPathNameW(w "$TEMP", w .r12, i 1024)'
  ${If} $R2 == ""
    StrCpy $R2 "$TEMP"
  ${EndIf}
  StrCpy $R3 "$R1\code"                 ; code destination directory
  StrCpy $R4 "$R2\easyokapi_app.tar.gz" ; temp download archive

  ; ── Inject token into child-process environment ───────────────────────────────
  StrCpy $R0 "$EasyOKAPIToken"
  System::Call 'Kernel32::SetEnvironmentVariableW(w "EASYOKAPI_DOWNLOAD_TOKEN", w r10) i .r1'
  ${If} $1 == 0
    MessageBox MB_OK|MB_ICONSTOP "Installer error: could not set download token in process environment.$\r$\nPlease re-run Setup."
    Abort
  ${EndIf}

  ; ── Step 1 / 3  -  Downloading application ───────────────────────────────────
  DetailPrint "======================================"
  DetailPrint "Step 1 / 3  -  Downloading application"
  DetailPrint "======================================"

  ; Detect existing installation and ask the user what to do.
  StrCpy $R5 "0"
  StrCpy $R6 ""
  IfFileExists "$R3" 0 step1_fresh      ; exists → fall through; absent → jump

    ; Read the installed version from VERSION.txt (if present).
    StrCpy $R7 "Unknown"
    IfFileExists "$R3\VERSION.txt" 0 +4
      FileOpen $8 "$R3\VERSION.txt" r
      FileRead $8 $R7
      FileClose $8

    ; Ask the user: update or keep?
    MessageBox MB_YESNO|MB_ICONQUESTION \
      "An existing EasyOKAPI installation was found:$\r$\n\
$\r$\n\
    Location:        $R3$\r$\n\
    Current version: $R7$\r$\n\
    New version:     v${APP_VERSION}$\r$\n\
$\r$\n\
Update to v${APP_VERSION}? (Your data will be preserved.) \
Click No to keep the existing installation and cancel Setup." \
      IDYES step1_do_overwrite
      Abort   ; user chose No → exit installer cleanly
    step1_do_overwrite:

    DetailPrint "Existing installation found — preserving user data..."
    StrCpy $R6 "$R2\easyokapi_backup"
    CreateDirectory "$R6"
    StrCpy $R5 "1"
    IfFileExists "$R3\data\*.*" 0 +2
      CopyFiles /SILENT "$R3\data" "$R6\data"
    IfFileExists "$R3\json\*.*" 0 +2
      CopyFiles /SILENT "$R3\json" "$R6\json"
    IfFileExists "$R3\report\*.*" 0 +2
      CopyFiles /SILENT "$R3\report" "$R6\report"
    DetailPrint "Removing existing code directory for overwrite..."
    RMDir /r "$R3"
  step1_fresh:
  CreateDirectory "$R3"

  ; Download — curl output goes straight to the NSIS detail log.
  DetailPrint "Downloading application archive..."
  nsExec::ExecToLog '"cmd.exe" /c curl --fail -L -o "$R4" "${AUTH_BASE_URL}/api/download?token=%EASYOKAPI_DOWNLOAD_TOKEN%"'
  Pop $0
  ${If} $0 == 255
    MessageBox MB_OK|MB_ICONSTOP "curl could not be launched (exit 255).$\r$\nCheck antivirus / Defender exclusions for $INSTDIR, then re-run Setup."
    Abort
  ${EndIf}
  ${If} $0 != 0
    MessageBox MB_OK|MB_ICONSTOP "Download failed (curl exit $0).$\r$\nCheck your token and internet connection.$\r$\nSee the detail log above for curl's error output."
    Abort
  ${EndIf}

  ; Extract — tar output goes straight to the NSIS detail log.
  DetailPrint "Extracting application archive..."
  nsExec::ExecToLog '"cmd.exe" /c tar -xzf "$R4" -C "$R3" --strip-components=1'
  Pop $0
  Delete "$R4"
  ${If} $0 != 0
    MessageBox MB_OK|MB_ICONSTOP "Extraction failed (tar exit $0).$\r$\nSee the detail log above for more information."
    Abort
  ${EndIf}

  ; Restore preserved user data.
  ${If} $R5 == "1"
    DetailPrint "Restoring user data (data, json, report)..."
    IfFileExists "$R6\data\*.*" 0 +2
      CopyFiles /SILENT "$R6\data" "$R3\data"
    IfFileExists "$R6\json\*.*" 0 +2
      CopyFiles /SILENT "$R6\json" "$R3\json"
    IfFileExists "$R6\report\*.*" 0 +2
      CopyFiles /SILENT "$R6\report" "$R3\report"
    RMDir /r "$R6"
    DetailPrint "User data restored."
  ${EndIf}

  ; Remove development-only files from the extracted archive.
  DetailPrint "Removing development files..."
  Delete "$R3\*.command"
  Delete "$R3\*.bat"
  Delete "$R3\log_hid_data.py"
  Delete "$R3\generate-tree.sh"
  Delete "$R3\BUILD_MAC.md"
  Delete "$R3\Rule.md"
  RMDir /r "$R3\mac"
  RMDir /r "$R3\easyokapi-knowledge"
  RMDir /r "$R3\images"
  RMDir /r "$R3\installer-mac"
  RMDir /r "$R3\installer-win"
  RMDir /r "$R3\installer-linux"
  RMDir /r "$R3\tests"
  RMDir /r "$R3\.github"

  ; Write version and activation files.
  FileOpen $9 "$R3\VERSION.txt" w
  FileWrite $9 "v${APP_VERSION}"
  FileClose $9
  FileOpen $9 "$R3\activation.json" w
  FileWrite $9 '{$\n  "license_token": "$EasyOKAPIToken"$\n}'
  FileClose $9

  DetailPrint "Application downloaded successfully."

  ; ── Step 2 / 3  -  Installing pyenv & Python ─────────────────────────────────
  DetailPrint "======================================"
  DetailPrint "Step 2 / 3  -  Installing pyenv & Python"
  DetailPrint "======================================"
  nsExec::ExecToLog '"cmd.exe" /c "$R1\startwindow-2-pyenv.bat"'
  Pop $0
  ${If} $0 != 0
    MessageBox MB_OK|MB_ICONSTOP "pyenv setup failed (exit code $0).$\r$\nCheck that you have an internet connection and re-run Setup."
    Abort
  ${EndIf}
  nsExec::ExecToLog '"cmd.exe" /c "$R1\startwindow-3-python.bat"'
  Pop $0
  ${If} $0 != 0
    MessageBox MB_OK|MB_ICONSTOP "Python installation failed (exit code $0).$\r$\nCheck the Detail log above for the error, then re-run Setup."
    Abort
  ${EndIf}
  DetailPrint "Python ready."

  DetailPrint "======================================"
  DetailPrint "Step 3 / 3  -  Setting up virtual environment"
  DetailPrint "======================================"
  nsExec::ExecToLog '"cmd.exe" /c "$R1\startwindow-4-venv.bat"'
  Pop $0
  ${If} $0 != 0
    MessageBox MB_OK|MB_ICONSTOP "Virtual environment setup failed (exit code $0).$\r$\nCheck the Detail log above for the error, then re-run Setup."
    Abort
  ${EndIf}
  DetailPrint "Virtual environment ready."

  ; Create desktop shortcut and write uninstaller
  CreateShortCut "$DESKTOP\${APP_NAME}.lnk" "$INSTDIR\${RUNNER_NAME}.exe"
  WriteUninstaller "$INSTDIR\Uninstall.exe"

  DetailPrint ""
  DetailPrint "EasyOKAPI ${APP_VERSION} installed successfully."
SectionEnd

; ── Uninstall section ──────────────────────────────────────────────────────────
Section "Uninstall"
  ExecWait 'net stop "${RUNNER_NAME}"'
  ExecWait '"$INSTDIR\nssm.exe" remove "${RUNNER_NAME}" confirm'
  Delete "$SMPROGRAMS\${APP_NAME}\*.*"
  RMDir "$SMPROGRAMS\${APP_NAME}"

  ; Preserve user data before wiping the install directory
  CreateDirectory "$DOCUMENTS\EasyOKAPI_data"
  IfFileExists "$INSTDIR\code\data\*.*" 0 +2
    CopyFiles /SILENT "$INSTDIR\code\data" "$DOCUMENTS\EasyOKAPI_data\data"
  IfFileExists "$INSTDIR\code\json\*.*" 0 +2
    CopyFiles /SILENT "$INSTDIR\code\json" "$DOCUMENTS\EasyOKAPI_data\json"
  IfFileExists "$INSTDIR\code\report\*.*" 0 +2
    CopyFiles /SILENT "$INSTDIR\code\report" "$DOCUMENTS\EasyOKAPI_data\report"
  MessageBox MB_OK "Your measurement data, calibration curves, and reports have been saved to:$\r$\n$DOCUMENTS\EasyOKAPI_data"

  Delete "$INSTDIR\startwindow-0-clone-repo.bat"
  Delete "$INSTDIR\startwindow-2-pyenv.bat"
  Delete "$INSTDIR\startwindow-3-python.bat"
  Delete "$INSTDIR\startwindow-4-venv.bat"
  Delete "$INSTDIR\startwindow-5-run.bat"
  Delete "$INSTDIR\launcher.ps1"
  Delete "$INSTDIR\${RUNNER_NAME}.exe"
  Delete "$INSTDIR\ht.ico"
  Delete "$INSTDIR\code\*.*"
  Delete "$DESKTOP\${APP_NAME}.lnk"
  Delete "$INSTDIR\Uninstall.exe"

  RMDir /r "$INSTDIR"
SectionEnd
