; setup-frozen.nsi — installer for the no-source (PyInstaller) Windows build.
;
; Unlike setup.nsi (the source build) this bundles the frozen onedir
; (..\dist\EasyOKAPI\) directly into the installer — no token page, no download,
; no git/pyenv/python/venv. Running the app needs no admin (CDC serial, not HID);
; only installing does.
;
; User data (data/json/report/log) lives in a VISIBLE folder the user can open:
; Documents\EasyOKAPI (matches src/state.py). It is migrated once from an older
; frozen build's hidden %LOCALAPPDATA%\EasyOKAPI and from any old source install
; ($INSTDIR\code\). Bundled sample data / demo curves are offered by the app on
; first run, not by this installer.
;
; Compile from inside installer-win/ (like setup.nsi) so NSIS resolves the
; relative paths (setup.ico, bitmaps, ..\dist) against this script's directory:
;   cd installer-win && makensis /DAPP_VERSION=1.1.8 setup-frozen.nsi

!define APP_NAME "EasyOKAPI"
!ifndef APP_VERSION
  !error "APP_VERSION is not defined. Pass it with: makensis /DAPP_VERSION=x.x.x setup-frozen.nsi"
!endif
!define INSTALL_DIR "$PROGRAMFILES64\EasyOKAPI"
!define UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}"

!define MUI_ICON "setup.ico"
!define MUI_UNICON "setup.ico"

; ── Branding bitmaps (generated by installer-win/build-bitmaps.py) ────────────
!define MUI_WELCOMEFINISHPAGE_BITMAP "sidebar.bmp"
!define MUI_HEADERIMAGE
!define MUI_HEADERIMAGE_BITMAP "header.bmp"
!define MUI_HEADERIMAGE_RIGHT

; ── Dark-theme colour palette (matches the EasyOKAPI web app) ─────────────────
!define CLR_BG     "312E81"  ; indigo-900
!define CLR_FG     "E2E8F0"  ; slate-200
!define CLR_INPUT  "1E1B4B"  ; indigo-950
!define CLR_ACCENT "6366F1"  ; indigo-500

!define MUI_ABORTWARNING
!define MUI_ABORTWARNING_TEXT "Are you sure you want to cancel the EasyOKAPI installation?"

; Welcome page
!define MUI_WELCOMEPAGE_TITLE "Welcome to EasyOKAPI Setup"
!define MUI_WELCOMEPAGE_TEXT "This will install EasyOKAPI ${APP_VERSION} (no-source build).$\r$\n$\r$\nEverything is bundled — no internet connection, token, or Python install is required. Your measurement data, calibration curves, and reports are kept in your Documents\EasyOKAPI folder and preserved across updates.$\r$\n$\r$\nClick Next to continue."

; Finish page — launch the app, and a checkbox to open the data folder.
!define MUI_FINISHPAGE_TITLE "EasyOKAPI ${APP_VERSION} Installed"
!define MUI_FINISHPAGE_TEXT "EasyOKAPI has been installed and Desktop + Start Menu shortcuts created.$\r$\n$\r$\nYour data lives in Documents\EasyOKAPI and is preserved across updates."
!define MUI_FINISHPAGE_RUN "$INSTDIR\EasyOKAPI.exe"
!define MUI_FINISHPAGE_RUN_PARAMETERS "--port 5099 --alias 127.0.0.1"
!define MUI_FINISHPAGE_RUN_TEXT "Launch EasyOKAPI now"
!define MUI_FINISHPAGE_SHOWREADME ""
!define MUI_FINISHPAGE_SHOWREADME_NOTCHECKED
!define MUI_FINISHPAGE_SHOWREADME_TEXT "Open my EasyOKAPI data folder"
!define MUI_FINISHPAGE_SHOWREADME_FUNCTION OpenDataFolder

RequestExecutionLevel admin
SetCompressor /SOLID lzma

; Background images for the dark theme (extracted to $PLUGINSDIR in _OnInit).
ReserveFile "background.bmp"
ReserveFile "page_bg.bmp"

; Install-log text / background on the InstFiles detail area
InstallColors E2E8F0 312E81

Name "${APP_NAME} ${APP_VERSION}"
OutFile "EasyOKAPI_Setup_${APP_VERSION}_frozen.exe"
InstallDir "${INSTALL_DIR}"
BrandingText "EasyOKAPI ${APP_VERSION}"
ShowInstDetails show
ShowUninstDetails show

!include "MUI2.nsh"
!include "WinMessages.nsh"
!include "LogicLib.nsh"

; ── Page order: Welcome → Directory → Install → Finish ───────────────────────
; Each MUI page gets a SHOW callback that recolours the inner controls. The
; uninstaller keeps the default theme (its callbacks would need un. twins).
!define MUI_PAGE_CUSTOMFUNCTION_SHOW _DarkWelcomePage
!insertmacro MUI_PAGE_WELCOME

!define MUI_PAGE_CUSTOMFUNCTION_SHOW _DarkPage
!insertmacro MUI_PAGE_DIRECTORY

!define MUI_PAGE_CUSTOMFUNCTION_SHOW _DarkInstPage
!insertmacro MUI_PAGE_INSTFILES

!define MUI_PAGE_CUSTOMFUNCTION_SHOW _DarkPage
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

; MUI2 owns .onInit and .onGUIInit — use these hooks for our customisations.
!define MUI_CUSTOMFUNCTION_INIT     _OnInit
!define MUI_CUSTOMFUNCTION_GUIINIT  _OnGUIInit

!insertmacro MUI_LANGUAGE "English"

; ── Background image ──────────────────────────────────────────────────────────
; _OnInit runs inside MUI2's .onInit before any window is created. Only extracts
; the bitmaps here; BgImage::SetBg is called in _OnGUIInit (a window must exist
; first, or BgImage loses Z-order on Win10/11 and never shows).
Function _OnInit
  InitPluginsDir
  SetOutPath $PLUGINSDIR
  File "background.bmp"
  File "page_bg.bmp"
FunctionEnd

Function .onGUIEnd
  BgImage::Destroy
FunctionEnd

; _DarkWelcomePage — SHOW callback for the Welcome page. Applies the indigo dark
; theme (via _DarkPage) then injects the scaled background behind the inner
; dialog. If LoadImageW fails the blank control is destroyed and the indigo
; fallback remains. SS_BITMAP controls (the okapi sidebar) are left alone.
Function _DarkWelcomePage
  Call _DarkPage

  Push $R6
  Push $R7
  Push $R8
  Push $R9

  FindWindow $R8 "#32770" "" $HWNDPARENT
  ${If} $R8 != 0
    System::Alloc 16
    Pop $R9
    System::Call 'user32::GetClientRect(i $R8, i $R9)'
    System::Call '*$R9(i, i, i .r0, i .r1)'   ; r0 = width, r1 = height
    System::Free $R9

    System::Call 'user32::CreateWindowExW(i 0, t "STATIC", t "", i 0x5000000E, i 0, i 0, i r0, i r1, i $R8, i 0, i 0, i 0) i .R7'

    System::Call 'user32::LoadImageW(i 0, t "$PLUGINSDIR\page_bg.bmp", i 0, i 0, i 0, i 0x10) i .R6'

    ${If} $R6 != 0
      SendMessage $R7 0x172 0 $R6   ; STM_SETIMAGE (0x172), IMAGE_BITMAP (0)
      System::Call 'user32::SetWindowPos(i $R7, i 1, i 0, i 0, i r0, i r1, i 0)'

      StrCpy $R9 0
      _dwp_loop:
        System::Call 'user32::FindWindowEx(i $R8, i $R9, i 0, i 0) i .R9'
        ${If} $R9 == 0
          Goto _dwp_done
        ${EndIf}
        ${If} $R9 == $R7
          Goto _dwp_loop
        ${EndIf}
        System::Call 'user32::GetWindowLongW(i $R9, i -16) i .R6'
        IntOp $R6 $R6 & 0xF
        ${If} $R6 == 0xE   ; SS_BITMAP — leave sidebar.bmp alone
          Goto _dwp_loop
        ${EndIf}
        SetCtlColors $R9 "${CLR_FG}" "transparent"
        Goto _dwp_loop
      _dwp_done:

      System::Call 'user32::InvalidateRect(i $R8, i 0, i 1)'
    ${Else}
      System::Call 'user32::DestroyWindow(i $R7)'
    ${EndIf}
  ${EndIf}

  Pop $R9
  Pop $R8
  Pop $R7
  Pop $R6

  Call _DarkButtons
FunctionEnd

; _DarkPage — called from every page SHOW callback. Two-level walk: applies the
; dark palette to every direct child of the inner dialog, then each grandchild
; (e.g. the Browse button / path edit inside the Destination groupbox).
Function _DarkPage
  Push $R6
  Push $R7
  Push $R8
  Push $R9

  FindWindow $R8 "#32770" "" $HWNDPARENT
  ${If} $R8 == 0
    Pop $R9
    Pop $R8
    Pop $R7
    Pop $R6
    Return
  ${EndIf}
  SetCtlColors $R8 "${CLR_FG}" "${CLR_BG}"

  StrCpy $R9 0
  _dp_loop:
    System::Call 'user32::FindWindowEx(i $R8, i $R9, i 0, i 0) i .R9'
    ${If} $R9 == 0
      Goto _dp_done
    ${EndIf}
    System::Call 'uxtheme::SetWindowTheme(i $R9, w " ", w " ")'
    SetCtlColors $R9 "${CLR_FG}" "${CLR_BG}"

    StrCpy $R7 0
    _dp_gc_loop:
      System::Call 'user32::FindWindowEx(i $R9, i $R7, i 0, i 0) i .R7'
      ${If} $R7 == 0
        Goto _dp_gc_done
      ${EndIf}
      System::Call 'uxtheme::SetWindowTheme(i $R7, w " ", w " ")'
      SetCtlColors $R7 "${CLR_FG}" "${CLR_INPUT}"
      Goto _dp_gc_loop
    _dp_gc_done:

    Goto _dp_loop
  _dp_done:

  Pop $R9
  Pop $R8
  Pop $R7
  Pop $R6
FunctionEnd

; _DarkInstPage — _DarkPage plus progress-bar + detail-log colour overrides.
Function _DarkInstPage
  Call _DarkPage

  Push $R7
  Push $R8

  FindWindow $R8 "#32770" "" $HWNDPARENT
  ${If} $R8 == 0
    Pop $R8
    Pop $R7
    Return
  ${EndIf}

  System::Call 'user32::FindWindowEx(i $R8, i 0, t "msctls_progress32", i 0) i .R7'
  ${If} $R7 != 0
    System::Call 'uxtheme::SetWindowTheme(i $R7, w " ", w " ")'
    SendMessage $R7 0x0409 0 0x00F16663   ; PBM_SETBARCOLOR — indigo-500
    SendMessage $R7 0x2001 0 0x002A170F   ; PBM_SETBKCOLOR  — slate-900
  ${EndIf}

  System::Call 'user32::FindWindowEx(i $R8, i 0, t "RichEdit20W", i 0) i .R7'
  ${If} $R7 == 0
    System::Call 'user32::FindWindowEx(i $R8, i 0, t "EDIT", i 0) i .R7'
  ${EndIf}
  ${If} $R7 != 0
    System::Call 'uxtheme::SetWindowTheme(i $R7, w "DarkMode_Explorer", i 0)'
    SetCtlColors $R7 "${CLR_FG}" "${CLR_BG}"
  ${EndIf}

  Pop $R8
  Pop $R7
FunctionEnd

; _DarkButtons — indigo fill on every BUTTON child of the outer window.
Function _DarkButtons
  Push $R0
  StrCpy $R0 0
  _dbtn_loop:
    System::Call 'user32::FindWindowEx(i $HWNDPARENT, i $R0, t "Button", i 0) i .R0'
    ${If} $R0 == 0
      Goto _dbtn_done
    ${EndIf}
    System::Call 'uxtheme::SetWindowTheme(i $R0, w " ", w " ")'
    SetCtlColors $R0 "${CLR_FG}" "${CLR_ACCENT}"
    Goto _dbtn_loop
  _dbtn_done:
  Pop $R0
FunctionEnd

; _OnGUIInit — colours the outer chrome, title bar, buttons and BrandingText,
; and starts the BgImage background (the outer window now exists).
Function _OnGUIInit
  BgImage::SetBg /NOUNLOAD "$PLUGINSDIR\background.bmp"
  BgImage::Redraw /NOUNLOAD

  SetCtlColors $HWNDPARENT "${CLR_FG}" "${CLR_BG}"

  System::Call 'dwmapi::DwmSetWindowAttribute(i $HWNDPARENT, i 35, *i 0x00F16663, i 4)'
  System::Call 'dwmapi::DwmSetWindowAttribute(i $HWNDPARENT, i 36, *i 0x00FFFFFF, i 4)'

  Call _DarkButtons

  Push $R0
  StrCpy $R0 0
  _branding_loop:
    System::Call 'user32::FindWindowEx(i $HWNDPARENT, i $R0, t "Static", i 0) i .R0'
    ${If} $R0 == 0
      Goto _branding_done
    ${EndIf}
    SetCtlColors $R0 "A5B4FC" "${CLR_BG}"
    Goto _branding_loop
  _branding_done:
  Pop $R0
FunctionEnd

; Finish-page checkbox — open the user's data folder in Explorer.
Function OpenDataFolder
  ExecShell "open" "$DOCUMENTS\EasyOKAPI"
FunctionEnd

; Merge SRC into DST without overwriting newer/existing files (robocopy /XO skips
; older source files; existing same-time files are skipped). Exit codes 0-7 = ok.
!macro MigrateDir SRC DST
  IfFileExists "${SRC}\*.*" 0 +3
    nsExec::ExecToLog 'robocopy "${SRC}" "${DST}" /E /XO /NJH /NJS /NFL /NDL /NC /NS /NP'
    Pop $0
!macroend

Section "Install" SEC01
  StrCpy $R0 "$DOCUMENTS\EasyOKAPI"   ; visible per-user data root (matches state.py)

  ; ── Refuse to overwrite a running instance ──────────────────────────────────
  ; A live EasyOKAPI.exe keeps its files open, so File /r below would fail. It may
  ; run elevated, so we cannot force-kill it — ask the user to close it and retry.
  InitPluginsDir
  FileOpen $9 "$PLUGINSDIR\detect-easyokapi.ps1" w
  FileWrite $9 "$$r = $$args[0]$\r$\n"
  FileWrite $9 "$$p = Get-CimInstance Win32_Process | Where-Object { $$_.Name -eq 'EasyOKAPI.exe' -and $$_.ExecutablePath -and $$_.ExecutablePath.StartsWith($$r,[System.StringComparison]::OrdinalIgnoreCase) }$\r$\n"
  FileWrite $9 "if ($$p) { exit 1 } else { exit 0 }$\r$\n"
  FileClose $9
  check_running:
  IfFileExists "$INSTDIR\EasyOKAPI.exe" 0 not_running
    DetailPrint "Checking for a running EasyOKAPI instance..."
    nsExec::ExecToLog '"powershell.exe" -NoProfile -ExecutionPolicy Bypass -File "$PLUGINSDIR\detect-easyokapi.ps1" "$INSTDIR\"'
    Pop $0
    ${If} $0 == 1
      MessageBox MB_RETRYCANCEL|MB_ICONEXCLAMATION \
        "EasyOKAPI is still running and must be closed before it can be updated.$\r$\n\
$\r$\n\
Close the EasyOKAPI window (or open http://localhost:5099 and click the \
$\"Shutdown Program$\" button), then click Retry.$\r$\n\
$\r$\n\
Click Cancel to exit Setup without making any changes." \
        IDRETRY check_running
      Abort
    ${EndIf}
  not_running:

  ; ── Migrate data into the visible folder (once) ─────────────────────────────
  ; Shares the .migrated_appdata marker with state.py so app + installer migrate
  ; exactly once. Sources: an older frozen build's hidden %LOCALAPPDATA%\EasyOKAPI,
  ; and an old source install ($INSTDIR\code\{data,json,report,log}).
  IfFileExists "$R0\.migrated_appdata" skip_migrate 0
    DetailPrint "Migrating existing data into $R0..."
    CreateDirectory "$R0"
    !insertmacro MigrateDir "$LOCALAPPDATA\EasyOKAPI\data"   "$R0\data"
    !insertmacro MigrateDir "$LOCALAPPDATA\EasyOKAPI\json"   "$R0\json"
    !insertmacro MigrateDir "$LOCALAPPDATA\EasyOKAPI\report" "$R0\report"
    !insertmacro MigrateDir "$LOCALAPPDATA\EasyOKAPI\log"    "$R0\log"
    !insertmacro MigrateDir "$INSTDIR\code\data"   "$R0\data"
    !insertmacro MigrateDir "$INSTDIR\code\json"   "$R0\json"
    !insertmacro MigrateDir "$INSTDIR\code\report" "$R0\report"
    !insertmacro MigrateDir "$INSTDIR\code\log"    "$R0\log"
    IfFileExists "$R0\activation.json" +2 0
      CopyFiles /SILENT "$INSTDIR\code\activation.json" "$R0\activation.json"
    IfFileExists "$R0\user_settings.json" +2 0
      CopyFiles /SILENT "$INSTDIR\code\user_settings.json" "$R0\user_settings.json"
    FileOpen $9 "$R0\.migrated_appdata" w
    FileWrite $9 "1"
    FileClose $9
  skip_migrate:

  ; ── Remove any previous install payload (source code dir + old runner) ──────
  RMDir /r "$INSTDIR\code"
  Delete "$INSTDIR\launcher.ps1"
  Delete "$INSTDIR\startwindow-*.bat"
  Delete "$INSTDIR\nssm.exe"

  ; ── Lay down the frozen onedir (EasyOKAPI.exe + _internal\) ─────────────────
  SetOutPath "$INSTDIR"
  File /r "..\dist\EasyOKAPI\*"

  ; ── Shortcuts ───────────────────────────────────────────────────────────────
  CreateShortCut "$DESKTOP\${APP_NAME}.lnk" "$INSTDIR\EasyOKAPI.exe" "--port 5099 --alias 127.0.0.1"
  CreateDirectory "$SMPROGRAMS\${APP_NAME}"
  CreateShortCut "$SMPROGRAMS\${APP_NAME}\${APP_NAME}.lnk" "$INSTDIR\EasyOKAPI.exe" "--port 5099 --alias 127.0.0.1"
  CreateShortCut "$SMPROGRAMS\${APP_NAME}\EasyOKAPI Data.lnk" "$R0"
  CreateShortCut "$SMPROGRAMS\${APP_NAME}\Uninstall ${APP_NAME}.lnk" "$INSTDIR\Uninstall.exe"

  WriteUninstaller "$INSTDIR\Uninstall.exe"

  ; ── Add/Remove Programs entry (Windows Settings > Apps) ──────────────────────
  WriteRegStr   HKLM "${UNINST_KEY}" "DisplayName"     "EasyOKAPI ${APP_VERSION}"
  WriteRegStr   HKLM "${UNINST_KEY}" "DisplayVersion"  "${APP_VERSION}"
  WriteRegStr   HKLM "${UNINST_KEY}" "DisplayIcon"     "$INSTDIR\EasyOKAPI.exe"
  WriteRegStr   HKLM "${UNINST_KEY}" "UninstallString" "$\"$INSTDIR\Uninstall.exe$\""
  WriteRegStr   HKLM "${UNINST_KEY}" "QuietUninstallString" "$\"$INSTDIR\Uninstall.exe$\" /S"
  WriteRegStr   HKLM "${UNINST_KEY}" "InstallLocation" "$INSTDIR"
  WriteRegStr   HKLM "${UNINST_KEY}" "Publisher"       "HTBiotec"
  WriteRegDWORD HKLM "${UNINST_KEY}" "NoModify"        1
  WriteRegDWORD HKLM "${UNINST_KEY}" "NoRepair"        1

  DetailPrint "EasyOKAPI ${APP_VERSION} installed. Data lives in $R0."
SectionEnd

Section "Uninstall"
  Delete "$DESKTOP\${APP_NAME}.lnk"
  Delete "$SMPROGRAMS\${APP_NAME}\*.*"
  RMDir  "$SMPROGRAMS\${APP_NAME}"
  DeleteRegKey HKLM "${UNINST_KEY}"
  Delete "$INSTDIR\Uninstall.exe"
  RMDir /r "$INSTDIR"
  ; User data in Documents\EasyOKAPI is intentionally left intact.
SectionEnd
