; setup-frozen.nsi — installer for the no-source (PyInstaller) Windows build.
;
; Unlike setup.nsi (the source build) this bundles the frozen onedir
; (..\dist\EasyOKAPI\) directly into the installer — no token page, no download,
; no git/pyenv/python/venv. Running the app needs no admin (CDC serial, not HID);
; only installing does.
;
; User data (data/json/report/log) lives in a VISIBLE folder the user can open.
; The Data Folder page lets the user choose where (default Documents\EasyOKAPI,
; matches src/state.py); a non-default choice is recorded in the
; $DOCUMENTS\.easyokapi_dataroot pointer the app + uninstaller read. It is
; migrated once from an older frozen build's hidden %LOCALAPPDATA%\EasyOKAPI and
; from any old source install ($INSTDIR\code\). Bundled sample data / demo curves
; are offered by the app on first run, not by this installer.
;
; Compile from inside installer-win/ (like setup.nsi) so NSIS resolves the
; relative paths (setup.ico, bitmaps, ..\dist) against this script's directory:
;   cd installer-win && makensis /DAPP_VERSION=1.2.8 setup-frozen.nsi

; Build a Unicode installer so accented characters and symbols in the on-screen
; text render correctly on every Windows language/locale (an ANSI installer shows
; them as garbage on non-Western code pages). MUST come before SetCompressor and
; ReserveFile (which start writing/compressing the output) or NSIS aborts with
; "Can't change target architecture after data already got compressed".
Unicode true

!define APP_NAME "EasyOKAPI"
!ifndef APP_VERSION
  !error "APP_VERSION is not defined. Pass it with: makensis /DAPP_VERSION=x.x.x setup-frozen.nsi"
!endif
!define INSTALL_DIR "$PROGRAMFILES64\EasyOKAPI"
!define UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}"

!define MUI_ICON "setup.ico"
!define MUI_UNICON "setup.ico"

; ── Branding bitmaps (generated by installer-win/build-bitmaps.py) ────────────
!define MUI_WELCOMEFINISHPAGE_BITMAP "sidebar.bmp"
!define MUI_HEADERIMAGE
!define MUI_HEADERIMAGE_BITMAP "header.bmp"
!define MUI_HEADERIMAGE_RIGHT

; ── Dark-theme colour palette (matches the EasyOKAPI web app) ─────────────────
!define CLR_BG     "312E81"  ; indigo-900
!define CLR_FG     "E2E8F0"  ; slate-200
!define CLR_INPUT  "1E1B4B"  ; indigo-950
!define CLR_ACCENT "6366F1"  ; indigo-500

!define MUI_ABORTWARNING
!define MUI_ABORTWARNING_TEXT "Are you sure you want to cancel the EasyOKAPI installation?"

; Welcome page
!define MUI_WELCOMEPAGE_TITLE "Welcome to the EasyOKAPI Setup"
!define MUI_WELCOMEPAGE_TEXT "This wizard will install EasyOKAPI ${APP_VERSION} on your computer.$\r$\n$\r$\nBefore you begin, please have your EasyOKAPI activation token ready and make sure you are connected to the internet. If you don't have a token yet, you can get one at easyokapi.cbbiotec.vn.$\r$\n$\r$\nYou can choose where your measurements, calibration curves and reports are saved (your Documents\EasyOKAPI folder by default), and they are kept safe whenever you update.$\r$\n$\r$\nClick Next to begin."

; Finish page: tick to start EasyOKAPI now (through the splash launcher). Note:
; Setup runs as administrator, so "Start now" launches the app elevated this one
; time - fine on a normal single-user machine where the same person installs and
; uses it. Day to day the user starts EasyOKAPI from the Desktop / Start Menu
; shortcut, which runs un-elevated. (The "open data folder" option was removed:
; the data root is created by the app on first run and can be relocated in-app.)
!define MUI_FINISHPAGE_TITLE "EasyOKAPI ${APP_VERSION} is ready"
!define MUI_FINISHPAGE_TEXT "EasyOKAPI has been installed. Shortcuts were added to your Desktop and Start Menu.$\r$\n$\r$\nYour measurements, calibration curves and reports are saved in the EasyOKAPI data folder you chose (use the $\"EasyOKAPI Data$\" Start Menu shortcut to open it)."
!define MUI_FINISHPAGE_RUN "$SYSDIR\WindowsPowerShell\v1.0\powershell.exe"
!define MUI_FINISHPAGE_RUN_PARAMETERS "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File $\"$INSTDIR\launcher-frozen.ps1$\""
!define MUI_FINISHPAGE_RUN_TEXT "Start EasyOKAPI now"

RequestExecutionLevel admin
SetCompressor /SOLID lzma

; Background images for the dark theme (extracted to $PLUGINSDIR in _OnInit).
ReserveFile "background.bmp"
ReserveFile "page_bg.bmp"

; Install-log text / background on the InstFiles detail area
InstallColors E2E8F0 312E81

Name "${APP_NAME} ${APP_VERSION}"
OutFile "EasyOKAPI_Setup_${APP_VERSION}.exe"
InstallDir "${INSTALL_DIR}"
BrandingText "EasyOKAPI ${APP_VERSION}"
ShowInstDetails show
ShowUninstDetails show

!include "MUI2.nsh"
!include "WinMessages.nsh"
!include "LogicLib.nsh"
!include "nsDialogs.nsh"

; Activation server for the download-token → permanent-license exchange. Must
; match the app's AI_SERVICE_URL default (src/activation.py) so the permanent
; token the app's AI proxy validates is issued by the same server. Override at
; compile time with /DACTIVATION_URL=https://...
!ifndef ACTIVATION_URL
  !define ACTIVATION_URL "https://www.easyokapi.cbbiotec.vn"
!endif

Var Dialog
Var TokenInput
Var EasyOKAPIToken
Var BgBitmapHandle
Var UninstVer
Var DataParent      ; parent folder chosen on the Data Folder page; root = $DataParent\EasyOKAPI
Var DataInput       ; text-field handle on the Data Folder page
Var DataBrowseBtn   ; Browse button handle on the Data Folder page

; ── Page order: Welcome → Token → Directory → DataFolder → Install → Finish ───
; Each MUI page gets a SHOW callback that recolours the inner controls. The
; uninstaller keeps the default theme (its callbacks would need un. twins).
!define MUI_PAGE_CUSTOMFUNCTION_SHOW _DarkWelcomePage
!insertmacro MUI_PAGE_WELCOME

; Required activation token (see TokenPage). The token is the license gate for
; the whole product: it is validated against the activation server on Leave, and
; installation cannot proceed without a valid one.
Page custom TokenPage TokenPageLeave

!define MUI_PAGE_CUSTOMFUNCTION_SHOW _DarkPage
!insertmacro MUI_PAGE_DIRECTORY

; Where to keep user data. Placed AFTER the Directory page so $INSTDIR is known
; and the data folder can be validated against the program folder (see
; DataFolderPageLeave). Themed to match the Token page.
Page custom DataFolderPage DataFolderPageLeave

!define MUI_PAGE_CUSTOMFUNCTION_SHOW _DarkInstPage
!insertmacro MUI_PAGE_INSTFILES

!define MUI_PAGE_CUSTOMFUNCTION_SHOW _DarkPage
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

; MUI2 owns .onInit and .onGUIInit — use these hooks for our customisations.
!define MUI_CUSTOMFUNCTION_INIT     _OnInit
!define MUI_CUSTOMFUNCTION_GUIINIT  _OnGUIInit

!insertmacro MUI_LANGUAGE "English"

; ── Background image ──────────────────────────────────────────────────────────
; _OnInit runs inside MUI2's .onInit before any window is created. Only extracts
; the bitmaps here; BgImage::SetBg is called in _OnGUIInit (a window must exist
; first, or BgImage loses Z-order on Win10/11 and never shows).
Function _OnInit
  InitPluginsDir
  SetOutPath $PLUGINSDIR
  File "background.bmp"
  File "page_bg.bmp"
  StrCpy $DataParent "$DOCUMENTS"   ; default data location = Documents\EasyOKAPI
FunctionEnd

Function .onGUIEnd
  BgImage::Destroy
FunctionEnd

; _DarkWelcomePage — SHOW callback for the Welcome page. Applies the indigo dark
; theme (via _DarkPage) then injects the scaled background behind the inner
; dialog. If LoadImageW fails the blank control is destroyed and the indigo
; fallback remains. SS_BITMAP controls (the okapi sidebar) are left alone.
Function _DarkWelcomePage
  Call _DarkPage

  Push $R6
  Push $R7
  Push $R8
  Push $R9

  FindWindow $R8 "#32770" "" $HWNDPARENT
  ${If} $R8 != 0
    System::Alloc 16
    Pop $R9
    System::Call 'user32::GetClientRect(i $R8, i $R9)'
    System::Call '*$R9(i, i, i .r0, i .r1)'   ; r0 = width, r1 = height
    System::Free $R9

    System::Call 'user32::CreateWindowExW(i 0, t "STATIC", t "", i 0x5000000E, i 0, i 0, i r0, i r1, i $R8, i 0, i 0, i 0) i .R7'

    System::Call 'user32::LoadImageW(i 0, t "$PLUGINSDIR\page_bg.bmp", i 0, i 0, i 0, i 0x10) i .R6'

    ${If} $R6 != 0
      SendMessage $R7 0x172 0 $R6   ; STM_SETIMAGE (0x172), IMAGE_BITMAP (0)
      System::Call 'user32::SetWindowPos(i $R7, i 1, i 0, i 0, i r0, i r1, i 0)'

      StrCpy $R9 0
      _dwp_loop:
        System::Call 'user32::FindWindowEx(i $R8, i $R9, i 0, i 0) i .R9'
        ${If} $R9 == 0
          Goto _dwp_done
        ${EndIf}
        ${If} $R9 == $R7
          Goto _dwp_loop
        ${EndIf}
        System::Call 'user32::GetWindowLongW(i $R9, i -16) i .R6'
        IntOp $R6 $R6 & 0xF
        ${If} $R6 == 0xE   ; SS_BITMAP — leave sidebar.bmp alone
          Goto _dwp_loop
        ${EndIf}
        SetCtlColors $R9 "${CLR_FG}" "transparent"
        Goto _dwp_loop
      _dwp_done:

      System::Call 'user32::InvalidateRect(i $R8, i 0, i 1)'
    ${Else}
      System::Call 'user32::DestroyWindow(i $R7)'
    ${EndIf}
  ${EndIf}

  Pop $R9
  Pop $R8
  Pop $R7
  Pop $R6

  Call _DarkButtons
FunctionEnd

; _DarkPage — called from every page SHOW callback. Two-level walk: applies the
; dark palette to every direct child of the inner dialog, then each grandchild
; (e.g. the Browse button / path edit inside the Destination groupbox).
Function _DarkPage
  Push $R6
  Push $R7
  Push $R8
  Push $R9

  FindWindow $R8 "#32770" "" $HWNDPARENT
  ${If} $R8 == 0
    Pop $R9
    Pop $R8
    Pop $R7
    Pop $R6
    Return
  ${EndIf}
  SetCtlColors $R8 "${CLR_FG}" "${CLR_BG}"

  StrCpy $R9 0
  _dp_loop:
    System::Call 'user32::FindWindowEx(i $R8, i $R9, i 0, i 0) i .R9'
    ${If} $R9 == 0
      Goto _dp_done
    ${EndIf}
    System::Call 'uxtheme::SetWindowTheme(i $R9, w " ", w " ")'
    SetCtlColors $R9 "${CLR_FG}" "${CLR_BG}"

    StrCpy $R7 0
    _dp_gc_loop:
      System::Call 'user32::FindWindowEx(i $R9, i $R7, i 0, i 0) i .R7'
      ${If} $R7 == 0
        Goto _dp_gc_done
      ${EndIf}
      System::Call 'uxtheme::SetWindowTheme(i $R7, w " ", w " ")'
      SetCtlColors $R7 "${CLR_FG}" "${CLR_INPUT}"
      Goto _dp_gc_loop
    _dp_gc_done:

    Goto _dp_loop
  _dp_done:

  Pop $R9
  Pop $R8
  Pop $R7
  Pop $R6
FunctionEnd

; _DarkInstPage — _DarkPage plus progress-bar + detail-log colour overrides.
Function _DarkInstPage
  Call _DarkPage

  Push $R7
  Push $R8

  FindWindow $R8 "#32770" "" $HWNDPARENT
  ${If} $R8 == 0
    Pop $R8
    Pop $R7
    Return
  ${EndIf}

  System::Call 'user32::FindWindowEx(i $R8, i 0, t "msctls_progress32", i 0) i .R7'
  ${If} $R7 != 0
    System::Call 'uxtheme::SetWindowTheme(i $R7, w " ", w " ")'
    SendMessage $R7 0x0409 0 0x00F16663   ; PBM_SETBARCOLOR — indigo-500
    SendMessage $R7 0x2001 0 0x002A170F   ; PBM_SETBKCOLOR  — slate-900
  ${EndIf}

  System::Call 'user32::FindWindowEx(i $R8, i 0, t "RichEdit20W", i 0) i .R7'
  ${If} $R7 == 0
    System::Call 'user32::FindWindowEx(i $R8, i 0, t "EDIT", i 0) i .R7'
  ${EndIf}
  ${If} $R7 != 0
    System::Call 'uxtheme::SetWindowTheme(i $R7, w "DarkMode_Explorer", i 0)'
    SetCtlColors $R7 "${CLR_FG}" "${CLR_BG}"
  ${EndIf}

  Pop $R8
  Pop $R7
FunctionEnd

; _DarkButtons — indigo fill on every BUTTON child of the outer window.
Function _DarkButtons
  Push $R0
  StrCpy $R0 0
  _dbtn_loop:
    System::Call 'user32::FindWindowEx(i $HWNDPARENT, i $R0, t "Button", i 0) i .R0'
    ${If} $R0 == 0
      Goto _dbtn_done
    ${EndIf}
    System::Call 'uxtheme::SetWindowTheme(i $R0, w " ", w " ")'
    SetCtlColors $R0 "${CLR_FG}" "${CLR_ACCENT}"
    Goto _dbtn_loop
  _dbtn_done:
  Pop $R0
FunctionEnd

; _OnGUIInit — colours the outer chrome, title bar, buttons and BrandingText,
; and starts the BgImage background (the outer window now exists).
Function _OnGUIInit
  BgImage::SetBg /NOUNLOAD "$PLUGINSDIR\background.bmp"
  BgImage::Redraw /NOUNLOAD

  SetCtlColors $HWNDPARENT "${CLR_FG}" "${CLR_BG}"

  System::Call 'dwmapi::DwmSetWindowAttribute(i $HWNDPARENT, i 35, *i 0x00F16663, i 4)'
  System::Call 'dwmapi::DwmSetWindowAttribute(i $HWNDPARENT, i 36, *i 0x00FFFFFF, i 4)'

  Call _DarkButtons

  Push $R0
  StrCpy $R0 0
  _branding_loop:
    System::Call 'user32::FindWindowEx(i $HWNDPARENT, i $R0, t "Static", i 0) i .R0'
    ${If} $R0 == 0
      Goto _branding_done
    ${EndIf}
    SetCtlColors $R0 "A5B4FC" "${CLR_BG}"
    Goto _branding_loop
  _branding_done:
  Pop $R0
FunctionEnd

; ── EasyOKAPI activation-token page (required) ────────────────────────────────
; The token is the product's license gate: installation cannot proceed without a
; valid one. TokenPageLeave validates it against the activation server before the
; install begins. Themed to match the other pages (indigo bg + dark controls).
Function TokenPage
  !insertmacro MUI_HEADER_TEXT "EasyOKAPI Activation" "Enter your EasyOKAPI activation token to install (required)."
  nsDialogs::Create 1018
  Pop $Dialog
  ${If} $Dialog == error
    Abort
  ${EndIf}

  SetCtlColors $Dialog "${CLR_FG}" "${CLR_BG}"

  ; Background bitmap (created first so it sits at the back of the Z-order).
  ${NSD_CreateBitmap} 0 0 100% 100% ""
  Pop $0
  ${NSD_SetStretchedImage} $0 "$PLUGINSDIR\page_bg.bmp" $BgBitmapHandle

  ${NSD_CreateLabel} 0 0 100% 42u "Paste your EasyOKAPI activation token below. A valid token is required to install EasyOKAPI: it unlocks the application, the AI assistant, and automatic updates.$\r$\n$\r$\nDon't have a token yet? Get one at easyokapi.cbbiotec.vn. You will need an internet connection so we can check your token."
  Pop $0
  SetCtlColors $0 "${CLR_FG}" "${CLR_BG}"

  ${NSD_CreateText} 0 46u 100% 12u ""
  Pop $TokenInput
  SetCtlColors $TokenInput "${CLR_FG}" "${CLR_INPUT}"

  Call _DarkButtons
  nsDialogs::Show
FunctionEnd

; TokenPageLeave — enforce the license gate. Require a non-empty token, then
; validate it against ${ACTIVATION_URL}/api/activate. The exchange helper exits
; 0 (valid — permanent license written to $PLUGINSDIR\activation.json), 1 (token
; rejected: 4xx), or 2 (network/server error). The user cannot leave this page
; until a valid token is accepted, so an invalid token never installs the app.
Function TokenPageLeave
  ${NSD_GetText} $TokenInput $EasyOKAPIToken
  ${If} $EasyOKAPIToken == ""
    MessageBox MB_OK|MB_ICONEXCLAMATION "Please enter your EasyOKAPI activation token to continue. If you don't have one, you can get it at easyokapi.cbbiotec.vn."
    Abort
  ${EndIf}

  FileOpen $9 "$PLUGINSDIR\exchange-token.ps1" w
  FileWrite $9 "$$tok = $$args[0]; $$auth = $$args[1]; $$dest = $$args[2]$\r$\n"
  FileWrite $9 "try {$\r$\n"
  FileWrite $9 "  [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12$\r$\n"
  ; Compute this machine's hwid EXACTLY as the app does (src/hwid.py): SHA-256 of
  ; 'easyokapi-hwid-v1|win|<MachineGuid lowercased>'. Read MachineGuid from the
  ; 64-bit registry view so a 32-bit installer sees the same value Python's
  ; KEY_WOW64_64KEY read returns. The server binds the permanent token to this
  ; hwid, and the app re-checks it on launch — keep the two recipes in lockstep.
  FileWrite $9 "  $$hwid = 'unknown'$\r$\n"
  FileWrite $9 "  try {$\r$\n"
  FileWrite $9 "    $$base = [Microsoft.Win32.RegistryKey]::OpenBaseKey([Microsoft.Win32.RegistryHive]::LocalMachine, [Microsoft.Win32.RegistryView]::Registry64)$\r$\n"
  FileWrite $9 "    $$guid = $$base.OpenSubKey('SOFTWARE\Microsoft\Cryptography').GetValue('MachineGuid')$\r$\n"
  FileWrite $9 "    if ($$guid) { $$raw = $$guid.Trim().ToLower() } else { $$raw = 'unknown' }$\r$\n"
  FileWrite $9 "    $$canon = 'easyokapi-hwid-v1|win|' + $$raw$\r$\n"
  FileWrite $9 "    $$bytes = [System.Text.Encoding]::UTF8.GetBytes($$canon)$\r$\n"
  FileWrite $9 "    $$sha = [System.Security.Cryptography.SHA256]::Create()$\r$\n"
  FileWrite $9 "    $$hwid = ($$sha.ComputeHash($$bytes) | ForEach-Object { $$_.ToString('x2') }) -join ''$\r$\n"
  FileWrite $9 "  } catch {}$\r$\n"
  FileWrite $9 "  $$body = '{$\"token$\":$\"' + $$tok + '$\",$\"hwid$\":$\"' + $$hwid + '$\"}'$\r$\n"
  FileWrite $9 "  $$resp = Invoke-RestMethod -Method Post -Uri $\"$$auth/api/activate$\" -ContentType 'application/json' -Body $$body -TimeoutSec 15$\r$\n"
  FileWrite $9 "  if ($$resp.license_token) {$\r$\n"
  FileWrite $9 "    $$json = '{' + [char]10 + '  $\"license_token$\": $\"' + $$resp.license_token + '$\"' + [char]10 + '}'$\r$\n"
  FileWrite $9 "    [System.IO.File]::WriteAllText($$dest, $$json, (New-Object System.Text.UTF8Encoding($$false)))$\r$\n"
  FileWrite $9 "    exit 0$\r$\n"
  FileWrite $9 "  } else { exit 1 }$\r$\n"
  FileWrite $9 "} catch {$\r$\n"
  FileWrite $9 "  $$s = 0$\r$\n"
  FileWrite $9 "  try { $$s = [int]$$_.Exception.Response.StatusCode } catch {}$\r$\n"
  FileWrite $9 "  if ($$s -ge 400 -and $$s -lt 500) { exit 1 } else { exit 2 }$\r$\n"
  FileWrite $9 "}$\r$\n"
  FileClose $9

  nsExec::Exec '"powershell.exe" -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "$PLUGINSDIR\exchange-token.ps1" "$EasyOKAPIToken" "${ACTIVATION_URL}" "$PLUGINSDIR\activation.json"'
  Pop $0
  ${If} $0 == 0
    ; Valid token — permanent license staged. Allow the wizard to advance.
  ${ElseIf} $0 == 1
    MessageBox MB_OK|MB_ICONSTOP "That token could not be activated. It may be invalid or expired. Please get a fresh token at easyokapi.cbbiotec.vn, paste it, and click Next again."
    Abort
  ${Else}
    MessageBox MB_OK|MB_ICONEXCLAMATION "We couldn't reach the activation server to check your token. Please check your internet connection and click Next to try again."
    Abort
  ${EndIf}
FunctionEnd

; ── EasyOKAPI data-folder page ────────────────────────────────────────────────
; Lets the user pick WHERE their data lives. The chosen value is a *parent*
; folder; the data root is "<parent>\EasyOKAPI" (matches the in-app relocation
; semantics and src/data_root.py). Default is $DOCUMENTS. The app finds a
; non-default location through the $DOCUMENTS\.easyokapi_dataroot pointer the
; Install section writes (see Section "Install"). Themed like the Token page.
Function DataFolderPage
  !insertmacro MUI_HEADER_TEXT "EasyOKAPI Data Folder" "Choose where EasyOKAPI keeps your measurements and reports."
  nsDialogs::Create 1018
  Pop $Dialog
  ${If} $Dialog == error
    Abort
  ${EndIf}

  SetCtlColors $Dialog "${CLR_FG}" "${CLR_BG}"

  ; Background bitmap (created first so it sits at the back of the Z-order).
  ${NSD_CreateBitmap} 0 0 100% 100% ""
  Pop $0
  ${NSD_SetStretchedImage} $0 "$PLUGINSDIR\page_bg.bmp" $BgBitmapHandle

  ${NSD_CreateLabel} 0 0 100% 42u "Choose the folder where EasyOKAPI will store your measurements, calibration curves and reports. An $\"EasyOKAPI$\" folder is created inside the folder you pick.$\r$\n$\r$\nLeave the default (your Documents folder) unless you want your data on another drive or a shared location. You can also change this later from the app's Settings."
  Pop $0
  SetCtlColors $0 "${CLR_FG}" "${CLR_BG}"

  ${If} $DataParent == ""
    StrCpy $DataParent "$DOCUMENTS"
  ${EndIf}

  ${NSD_CreateText} 0 48u 74% 12u "$DataParent"
  Pop $DataInput
  SetCtlColors $DataInput "${CLR_FG}" "${CLR_INPUT}"

  ${NSD_CreateButton} 76% 47u 24% 14u "Browse..."
  Pop $DataBrowseBtn
  ${NSD_OnClick} $DataBrowseBtn DataFolderBrowse

  Call _DarkButtons
  nsDialogs::Show
FunctionEnd

; Browse button → native folder picker. Updates the text field with the choice.
Function DataFolderBrowse
  ${NSD_GetText} $DataInput $DataParent
  nsDialogs::SelectFolderDialog "Select the folder to store your EasyOKAPI data" "$DataParent"
  Pop $0
  ${If} $0 != error
    StrCpy $DataParent "$0"
    ${NSD_SetText} $DataInput "$DataParent"
  ${EndIf}
FunctionEnd

; DataFolderPageLeave — validate the chosen parent. The data root would be
; "$DataParent\EasyOKAPI". Reject an empty value and, crucially, refuse to place
; data inside the EasyOKAPI program folder ($INSTDIR) or anywhere under Program
; Files — those are read-only/elevated locations and would clash with the app's
; own in-app safeguard (src/data_root._validate_target). StrCmp ('==' in LogicLib)
; is case-insensitive, so typed-case variations are handled.
Function DataFolderPageLeave
  ${NSD_GetText} $DataInput $DataParent
  ${If} $DataParent == ""
    MessageBox MB_OK|MB_ICONEXCLAMATION "Please choose a folder for your EasyOKAPI data."
    Abort
  ${EndIf}

  StrCpy $R0 "$DataParent\EasyOKAPI"   ; the data root that would be created

  ; (1) Equal to the program folder, or the parent IS the program folder.
  StrLen $1 "$INSTDIR"
  StrCpy $2 "$DataParent" $1
  ${If} $DataParent == "$INSTDIR"
  ${OrIf} $R0 == "$INSTDIR"
  ${OrIf} $2 == "$INSTDIR"
    MessageBox MB_OK|MB_ICONSTOP "You can't store your data inside the EasyOKAPI program folder ($INSTDIR). Please choose a different location, such as your Documents folder."
    Abort
  ${EndIf}

  ; (2) Anywhere under Program Files (64- or 32-bit).
  StrLen $1 "$PROGRAMFILES64"
  StrCpy $2 "$DataParent" $1
  StrLen $3 "$PROGRAMFILES"
  StrCpy $4 "$DataParent" $3
  ${If} $2 == "$PROGRAMFILES64"
  ${OrIf} $4 == "$PROGRAMFILES"
    MessageBox MB_OK|MB_ICONSTOP "Program Files is not a good place for your data (it needs administrator rights to change). Please choose a folder such as your Documents folder or another drive."
    Abort
  ${EndIf}
FunctionEnd

; Merge SRC into DST without overwriting newer/existing files (robocopy /XO skips
; older source files; existing same-time files are skipped). Exit codes 0-7 = ok.
!macro MigrateDir SRC DST
  IfFileExists "${SRC}\*.*" 0 +3
    nsExec::ExecToLog 'robocopy "${SRC}" "${DST}" /E /XO /NJH /NJS /NFL /NDL /NC /NS /NP'
    Pop $0
!macroend

Section "Install" SEC01
  ; Data root = the folder chosen on the Data Folder page (default Documents\EasyOKAPI).
  StrCpy $R0 "$DataParent\EasyOKAPI"   ; per-user data root (matches state.py + pointer)

  ; ── Refuse to overwrite a running instance ──────────────────────────────────
  ; A live EasyOKAPI.exe keeps its files open, so File /r below would fail. It may
  ; run elevated, so we cannot force-kill it — ask the user to close it and retry.
  InitPluginsDir
  FileOpen $9 "$PLUGINSDIR\detect-easyokapi.ps1" w
  ; Bake $INSTDIR straight into the script (single-quoted) rather than passing it
  ; as an argument: a path ending in "\" inside quotes is mangled by command-line
  ; quote-escaping ( \" = escaped quote ), which silently broke the StartsWith
  ; match and made the check always report "not running". Two independent fail-safe
  ; signals: (1) any EasyOKAPI.exe whose image path is under the install dir — or
  ; whose path we cannot read — counts as running; (2) if EasyOKAPI.exe cannot be
  ; opened for writing, its files are locked = still in use. Exit 1 = running, 0 = clear.
  FileWrite $9 "$$r = '$INSTDIR'$\r$\n"
  FileWrite $9 "$$exe = Join-Path $$r 'EasyOKAPI.exe'$\r$\n"
  FileWrite $9 "$$procs = @(Get-CimInstance Win32_Process | Where-Object { $$_.Name -eq 'EasyOKAPI.exe' })$\r$\n"
  FileWrite $9 "foreach ($$p in $$procs) {$\r$\n"
  FileWrite $9 "  if (-not $$p.ExecutablePath) { exit 1 }$\r$\n"
  FileWrite $9 "  if ($$p.ExecutablePath.StartsWith($$r,[System.StringComparison]::OrdinalIgnoreCase)) { exit 1 }$\r$\n"
  FileWrite $9 "}$\r$\n"
  FileWrite $9 "if (Test-Path -LiteralPath $$exe) {$\r$\n"
  FileWrite $9 "  try { $$fs = [System.IO.File]::Open($$exe,'Open','ReadWrite','None'); $$fs.Close() } catch { exit 1 }$\r$\n"
  FileWrite $9 "}$\r$\n"
  FileWrite $9 "exit 0$\r$\n"
  FileClose $9
  check_running:
  IfFileExists "$INSTDIR\EasyOKAPI.exe" 0 not_running
    DetailPrint "Checking whether EasyOKAPI is already running..."
    nsExec::ExecToLog '"powershell.exe" -NoProfile -ExecutionPolicy Bypass -File "$PLUGINSDIR\detect-easyokapi.ps1"'
    Pop $0
    ${If} $0 == 1
      MessageBox MB_RETRYCANCEL|MB_ICONEXCLAMATION \
        "EasyOKAPI is currently open and needs to be closed before it can be updated.$\r$\n\
$\r$\n\
Please close the EasyOKAPI window, then click Retry. (If it is open in your web \
browser, go to http://localhost:5099 and click the $\"Shutdown Program$\" button first.)$\r$\n\
$\r$\n\
Click Cancel to exit without making any changes." \
        IDRETRY check_running
      Abort
    ${EndIf}
  not_running:

  ; ── Migrate data into the visible folder (once) ─────────────────────────────
  ; Shares the .migrated_appdata marker with state.py so app + installer migrate
  ; exactly once. Sources: an older frozen build's hidden %LOCALAPPDATA%\EasyOKAPI,
  ; and an old source install ($INSTDIR\code\{data,json,report,log}).
  IfFileExists "$R0\.migrated_appdata" skip_migrate 0
    DetailPrint "Bringing your existing measurements and settings into $R0..."
    CreateDirectory "$R0"
    !insertmacro MigrateDir "$LOCALAPPDATA\EasyOKAPI\data"   "$R0\data"
    !insertmacro MigrateDir "$LOCALAPPDATA\EasyOKAPI\json"   "$R0\json"
    !insertmacro MigrateDir "$LOCALAPPDATA\EasyOKAPI\report" "$R0\report"
    !insertmacro MigrateDir "$LOCALAPPDATA\EasyOKAPI\log"    "$R0\log"
    !insertmacro MigrateDir "$INSTDIR\code\data"   "$R0\data"
    !insertmacro MigrateDir "$INSTDIR\code\json"   "$R0\json"
    !insertmacro MigrateDir "$INSTDIR\code\report" "$R0\report"
    !insertmacro MigrateDir "$INSTDIR\code\log"    "$R0\log"
    IfFileExists "$R0\activation.json" +2 0
      CopyFiles /SILENT "$INSTDIR\code\activation.json" "$R0\activation.json"
    IfFileExists "$R0\user_settings.json" +2 0
      CopyFiles /SILENT "$INSTDIR\code\user_settings.json" "$R0\user_settings.json"
    FileOpen $9 "$R0\.migrated_appdata" w
    FileWrite $9 "1"
    FileClose $9
  skip_migrate:

  ; ── Restore data from the temporary EasyOKAPI_data folder, then remove it ────
  ; An in-app update stages a temporary safety copy in Documents\EasyOKAPI_data.
  ; Merge anything found there back into the working data folder (without
  ; overwriting newer files), then delete the temporary folder so it does not
  ; linger in Documents.
  StrCpy $R1 "$DOCUMENTS\EasyOKAPI_data"
  IfFileExists "$R1\*.*" 0 skip_restore
    DetailPrint "Restoring your data from $R1..."
    !insertmacro MigrateDir "$R1\data"   "$R0\data"
    !insertmacro MigrateDir "$R1\json"   "$R0\json"
    !insertmacro MigrateDir "$R1\report" "$R0\report"
    RMDir /r "$R1"
  skip_restore:

  ; ── Remove any previous install payload (source code dir + old runner) ──────
  RMDir /r "$INSTDIR\code"
  Delete "$INSTDIR\launcher.ps1"
  Delete "$INSTDIR\startwindow-*.bat"
  Delete "$INSTDIR\nssm.exe"

  ; ── Lay down the frozen onedir (EasyOKAPI.exe + _internal\) ─────────────────
  SetOutPath "$INSTDIR"
  File /r "..\dist\EasyOKAPI\*"

  ; ── Map easyokapi.com -> 127.0.0.1 so the app opens at a friendly address ────
  ; The app runs un-elevated and cannot edit the hosts file itself; do it here
  ; (Setup is elevated). Skipped if the mapping already exists.
  FileOpen $9 "$PLUGINSDIR\hosts-add.ps1" w
  FileWrite $9 "$$h = $\"$$env:windir\System32\drivers\etc\hosts$\"$\r$\n"
  FileWrite $9 "try {$\r$\n"
  FileWrite $9 "  $$c = Get-Content -Path $$h -ErrorAction SilentlyContinue$\r$\n"
  FileWrite $9 "  if (-not ($$c -match 'easyokapi\.com')) {$\r$\n"
  FileWrite $9 "    Add-Content -Path $$h -Value ''$\r$\n"
  FileWrite $9 "    Add-Content -Path $$h -Value '127.0.0.1 easyokapi.com'$\r$\n"
  FileWrite $9 "  }$\r$\n"
  FileWrite $9 "} catch {}$\r$\n"
  FileClose $9
  DetailPrint "Setting up the easyokapi.com address..."
  nsExec::ExecToLog '"powershell.exe" -NoProfile -ExecutionPolicy Bypass -File "$PLUGINSDIR\hosts-add.ps1"'
  Pop $0

  ; ── Shortcuts ───────────────────────────────────────────────────────────────
  ; Launch through launcher-frozen.ps1 so the user sees the "Starting EasyOKAPI"
  ; splash while the app loads (and a second click just reopens the browser). The
  ; shortcut still shows the EasyOKAPI icon; PowerShell runs hidden.
  !define _PS "$SYSDIR\WindowsPowerShell\v1.0\powershell.exe"
  !define _PSARGS '-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File $\"$INSTDIR\launcher-frozen.ps1$\"'
  CreateShortCut "$DESKTOP\${APP_NAME}.lnk" "${_PS}" "${_PSARGS}" "$INSTDIR\EasyOKAPI.exe" 0
  CreateDirectory "$SMPROGRAMS\${APP_NAME}"
  CreateShortCut "$SMPROGRAMS\${APP_NAME}\${APP_NAME}.lnk" "${_PS}" "${_PSARGS}" "$INSTDIR\EasyOKAPI.exe" 0
  CreateShortCut "$SMPROGRAMS\${APP_NAME}\EasyOKAPI Data.lnk" "$R0"
  CreateShortCut "$SMPROGRAMS\${APP_NAME}\Uninstall ${APP_NAME}.lnk" "$INSTDIR\Uninstall.exe"

  WriteUninstaller "$INSTDIR\Uninstall.exe"

  ; ── Add/Remove Programs entry (Windows Settings > Apps) ──────────────────────
  ; Registered under HKCU so the un-elevated app can rewrite DisplayVersion after
  ; an in-app binary-swap update (HKLM would need admin). Clear any stale HKLM
  ; entry an older installer wrote, so only one EasyOKAPI row is shown.
  DeleteRegKey  HKLM "${UNINST_KEY}"
  WriteRegStr   HKCU "${UNINST_KEY}" "DisplayName"     "EasyOKAPI ${APP_VERSION}"
  WriteRegStr   HKCU "${UNINST_KEY}" "DisplayVersion"  "${APP_VERSION}"
  WriteRegStr   HKCU "${UNINST_KEY}" "DisplayIcon"     "$INSTDIR\EasyOKAPI.exe"
  WriteRegStr   HKCU "${UNINST_KEY}" "UninstallString" "$\"$INSTDIR\Uninstall.exe$\""
  WriteRegStr   HKCU "${UNINST_KEY}" "QuietUninstallString" "$\"$INSTDIR\Uninstall.exe$\" /S"
  WriteRegStr   HKCU "${UNINST_KEY}" "InstallLocation" "$INSTDIR"
  WriteRegStr   HKCU "${UNINST_KEY}" "Publisher"       "HTBiotec"
  WriteRegDWORD HKCU "${UNINST_KEY}" "NoModify"        1
  WriteRegDWORD HKCU "${UNINST_KEY}" "NoRepair"        1

  ; ── Install the validated license ───────────────────────────────────────────
  ; The token was required and validated on the Token page (TokenPageLeave),
  ; which staged the permanent license token at $PLUGINSDIR\activation.json. Place
  ; it in the visible data folder where the app reads it. We never reach here with
  ; an invalid/empty token — the wizard cannot leave the Token page without one.
  CreateDirectory "$R0"
  CopyFiles /SILENT "$PLUGINSDIR\activation.json" "$R0\activation.json"

  ; ── Record a non-default data location ──────────────────────────────────────
  ; The app resolves its data root from a pointer file beside the default folder
  ; ($DOCUMENTS\.easyokapi_dataroot — see src/state._read_dataroot_override and the
  ; uninstaller below). Write it only when the user chose a folder other than the
  ; default Documents location; otherwise clear any stale pointer so the default
  ; wins. One line, no trailing CR/LF (the app's reader strips, but match the
  ; in-app writer which writes none).
  ${If} $DataParent == "$DOCUMENTS"
    Delete "$DOCUMENTS\.easyokapi_dataroot"
  ${Else}
    FileOpen $9 "$DOCUMENTS\.easyokapi_dataroot" w
    FileWrite $9 "$R0"
    FileClose $9
  ${EndIf}

  DetailPrint "EasyOKAPI ${APP_VERSION} is installed and activated. Your data is saved in $R0."
SectionEnd

; un.onInit — read the CURRENT installed version from VERSION.txt, which ships in
; the onedir and is carried by every in-app binary-swap update. This keeps the
; uninstaller's reported version in step with the running build instead of the
; (possibly older) version this uninstaller was compiled with. VERSION.txt is
; written without a trailing newline (tools/package.py), so FileRead yields the
; bare 'vX.Y.Z' token. Falls back to the compile-time version when absent.
Function un.onInit
  StrCpy $UninstVer "v${APP_VERSION}"
  ClearErrors
  FileOpen $9 "$INSTDIR\VERSION.txt" r
  IfErrors uv_done
    FileRead $9 $UninstVer
    FileClose $9
    StrCmp $UninstVer "" 0 uv_done
      StrCpy $UninstVer "v${APP_VERSION}"
  uv_done:
FunctionEnd

Section "Uninstall"
  ; ── Confirm before touching anything ────────────────────────────────────────
  ; A clear, last chance to back out. Nothing has been removed yet, so No leaves
  ; the installation exactly as it was.
  MessageBox MB_YESNO|MB_ICONQUESTION \
    "Are you sure you want to uninstall EasyOKAPI?$\r$\n$\r$\nClick No to cancel and keep EasyOKAPI installed." \
    IDYES un_confirmed
    Quit
  un_confirmed:

  DetailPrint "Uninstalling EasyOKAPI $UninstVer ..."

  ; ── Make sure EasyOKAPI is closed first ─────────────────────────────────────
  ; If it is still running its program files are locked, so they cannot be fully
  ; removed. Ask the user to close it and retry (same as the installer).
  InitPluginsDir
  FileOpen $9 "$PLUGINSDIR\detect-easyokapi.ps1" w
  ; Bake $INSTDIR straight into the script (single-quoted) rather than passing it
  ; as an argument: a path ending in "\" inside quotes is mangled by command-line
  ; quote-escaping ( \" = escaped quote ), which silently broke the StartsWith
  ; match and made the check always report "not running". Two independent fail-safe
  ; signals: (1) any EasyOKAPI.exe whose image path is under the install dir — or
  ; whose path we cannot read — counts as running; (2) if EasyOKAPI.exe cannot be
  ; opened for writing, its files are locked = still in use. Exit 1 = running, 0 = clear.
  FileWrite $9 "$$r = '$INSTDIR'$\r$\n"
  FileWrite $9 "$$exe = Join-Path $$r 'EasyOKAPI.exe'$\r$\n"
  FileWrite $9 "$$procs = @(Get-CimInstance Win32_Process | Where-Object { $$_.Name -eq 'EasyOKAPI.exe' })$\r$\n"
  FileWrite $9 "foreach ($$p in $$procs) {$\r$\n"
  FileWrite $9 "  if (-not $$p.ExecutablePath) { exit 1 }$\r$\n"
  FileWrite $9 "  if ($$p.ExecutablePath.StartsWith($$r,[System.StringComparison]::OrdinalIgnoreCase)) { exit 1 }$\r$\n"
  FileWrite $9 "}$\r$\n"
  FileWrite $9 "if (Test-Path -LiteralPath $$exe) {$\r$\n"
  FileWrite $9 "  try { $$fs = [System.IO.File]::Open($$exe,'Open','ReadWrite','None'); $$fs.Close() } catch { exit 1 }$\r$\n"
  FileWrite $9 "}$\r$\n"
  FileWrite $9 "exit 0$\r$\n"
  FileClose $9
  un_check_running:
  IfFileExists "$INSTDIR\EasyOKAPI.exe" 0 un_not_running
    nsExec::ExecToLog '"powershell.exe" -NoProfile -ExecutionPolicy Bypass -File "$PLUGINSDIR\detect-easyokapi.ps1"'
    Pop $0
    ${If} $0 == 1
      MessageBox MB_RETRYCANCEL|MB_ICONEXCLAMATION \
        "EasyOKAPI is currently open and needs to be closed before it can be removed.$\r$\n\
$\r$\n\
Please close the EasyOKAPI window, then click Retry. (If it is open in your web \
browser, go to http://localhost:5099 and click the $\"Shutdown Program$\" button first.)$\r$\n\
$\r$\n\
Click Cancel to stop removing EasyOKAPI." \
        IDRETRY un_check_running
      Quit   ; user chose Cancel → leave the installation untouched
    ${EndIf}
  un_not_running:

  ; ── Locate the user's data (it may have been relocated in-app) ──────────────
  ; The app can move the data root off Documents\EasyOKAPI. When it does it writes
  ; the new absolute path into a pointer file BESIDE the default folder
  ; ($DOCUMENTS\.easyokapi_dataroot — same path src/state.py uses). Read it so we
  ; act on the REAL data folder. $R7 = raw relocated path (may be ""/missing);
  ; $R3 = the folder we prompt about / back up (relocated if it exists, else default).
  StrCpy $R4 "$DOCUMENTS\.easyokapi_dataroot"   ; pointer file
  StrCpy $R7 ""                                  ; relocated data root (raw)
  StrCpy $R3 "$DOCUMENTS\EasyOKAPI"              ; folder to act on (default)
  ClearErrors
  FileOpen $8 "$R4" r
  IfErrors un_ptr_done
    FileRead $8 $R5
    FileClose $8
    ; Trim any trailing CR/LF the pointer might carry (the app writes none).
    un_ptr_trim:
      StrCpy $0 $R5 1 -1
      StrCmp $0 "$\r" un_ptr_strip 0
      StrCmp $0 "$\n" un_ptr_strip un_ptr_trimmed
      un_ptr_strip:
        StrCpy $R5 $R5 -1
        Goto un_ptr_trim
    un_ptr_trimmed:
    StrCmp $R5 "" un_ptr_done
      StrCpy $R7 $R5                             ; remember the relocated path
      IfFileExists "$R7\*.*" 0 un_ptr_done
        StrCpy $R3 $R7                           ; relocated folder exists → act on it
  un_ptr_done:

  ; ── Decide what to do with the user's data ──────────────────────────────────
  ; Default is to keep it. The user may choose to remove it, and (if so) to save a
  ; dated, versioned ZIP backup first. $R2: keep / removed / backedup / keepfail.
  StrCpy $R2 "keep"
  IfFileExists "$R3\*.*" 0 un_data_done
    MessageBox MB_YESNO|MB_ICONQUESTION \
      "Do you also want to remove your EasyOKAPI data (your measurements, calibration curves and reports)?$\r$\n$\r$\nClick No to keep your data in:$\r$\n$R3$\r$\n$\r$\nClick Yes to remove your data." \
      IDNO un_data_done
    MessageBox MB_YESNO|MB_ICONQUESTION \
      "Would you like to save a backup of your data (a ZIP file in your Documents folder) before it is removed?$\r$\n$\r$\nClick Yes to save a backup, then remove your data.$\r$\nClick No to remove your data without a backup." \
      IDNO un_mark_remove
    ; Yes: build a dated + versioned ZIP backup in Documents (best-effort).
    FileOpen $9 "$PLUGINSDIR\backup-zip.ps1" w
    FileWrite $9 "param($$src,$$ver,$$destDir)$\r$\n"
    FileWrite $9 "try {$\r$\n"
    FileWrite $9 "  Add-Type -AssemblyName System.IO.Compression.FileSystem$\r$\n"
    FileWrite $9 "  $$stamp = Get-Date -Format 'yyyy-MM-dd_HH-mm-ss'$\r$\n"
    FileWrite $9 "  $$zip = Join-Path $$destDir ('EasyOKAPI_backup_' + $$stamp + '_' + $$ver + '.zip')$\r$\n"
    FileWrite $9 "  if (Test-Path -LiteralPath $$zip) { Remove-Item -LiteralPath $$zip -Force }$\r$\n"
    FileWrite $9 "  [System.IO.Compression.ZipFile]::CreateFromDirectory($$src, $$zip)$\r$\n"
    FileWrite $9 "  exit 0$\r$\n"
    FileWrite $9 "} catch { exit 1 }$\r$\n"
    FileClose $9
    DetailPrint "Saving a backup ZIP of your data..."
    nsExec::ExecToLog '"powershell.exe" -NoProfile -ExecutionPolicy Bypass -File "$PLUGINSDIR\backup-zip.ps1" "$R3" "$UninstVer" "$DOCUMENTS"'
    Pop $0
    ${If} $0 == 0
      StrCpy $R2 "backedup"
    ${Else}
      StrCpy $R2 "keepfail"   ; backup failed -> keep the data, do not delete
    ${EndIf}
    Goto un_data_done
  un_mark_remove:
    StrCpy $R2 "removed"
  un_data_done:

  ; ── Shortcuts + Add/Remove Programs entry ───────────────────────────────────
  Delete "$DESKTOP\${APP_NAME}.lnk"
  Delete "$SMPROGRAMS\${APP_NAME}\*.*"
  RMDir  "$SMPROGRAMS\${APP_NAME}"
  DeleteRegKey HKCU "${UNINST_KEY}"
  DeleteRegKey HKLM "${UNINST_KEY}"

  ; ── Remove the easyokapi.com hosts mapping that Setup added ──────────────────
  FileOpen $9 "$PLUGINSDIR\hosts-del.ps1" w
  FileWrite $9 "$$h = $\"$$env:windir\System32\drivers\etc\hosts$\"$\r$\n"
  FileWrite $9 "try {$\r$\n"
  FileWrite $9 "  (Get-Content -Path $$h) | Where-Object { $$_ -notmatch 'easyokapi\.com' } | Set-Content -Path $$h$\r$\n"
  FileWrite $9 "} catch {}$\r$\n"
  FileClose $9
  nsExec::ExecToLog '"powershell.exe" -NoProfile -ExecutionPolicy Bypass -File "$PLUGINSDIR\hosts-del.ps1"'
  Pop $0

  ; ── Remove the program files completely ──────────────────────────────────────
  ; Move out of $INSTDIR first (a folder can't be deleted while it is the working
  ; directory). The uninstaller runs from a temporary copy of itself, so it can
  ; remove $INSTDIR\Uninstall.exe and the whole folder.
  SetOutPath "$TEMP"
  RMDir /r "$INSTDIR"

  ; ── Remove the data folders if the user asked to ────────────────────────────
  ; Remove the folder we acted on ($R3), the default folder + its update-backup
  ; sibling (a leftover copy may linger there after an in-app relocation), the
  ; relocated folder + its sibling ($R7, even if it was empty), and the pointer.
  ${If} $R2 == "removed"
  ${OrIf} $R2 == "backedup"
    RMDir /r "$R3"
    RMDir /r "$R3_data"
    RMDir /r "$DOCUMENTS\EasyOKAPI"
    RMDir /r "$DOCUMENTS\EasyOKAPI_data"
    StrCmp $R7 "" un_skip_reloc 0
      RMDir /r "$R7"
      RMDir /r "$R7_data"
    un_skip_reloc:
    Delete "$R4"
  ${EndIf}

  ; ── Tell the user what happened ──────────────────────────────────────────────
  ${If} $R2 == "removed"
    MessageBox MB_OK|MB_ICONINFORMATION "EasyOKAPI and all of your data have been completely removed."
  ${ElseIf} $R2 == "backedup"
    MessageBox MB_OK|MB_ICONINFORMATION "EasyOKAPI and your data have been removed.$\r$\n$\r$\nA backup ZIP of your data was saved in your Documents folder, named EasyOKAPI_backup_<date>_<time>_$UninstVer.zip."
  ${ElseIf} $R2 == "keepfail"
    MessageBox MB_OK|MB_ICONEXCLAMATION "EasyOKAPI has been removed.$\r$\n$\r$\nWe could not create the backup, so your data was kept (nothing was deleted) here:$\r$\n$R3"
  ${Else}
    MessageBox MB_OK|MB_ICONINFORMATION "EasyOKAPI has been removed.$\r$\n$\r$\nYour data was kept here:$\r$\n$R3"
  ${EndIf}
SectionEnd
